/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GdkPixbuf *main_window_icon_pixbuf;
  GtkWidget *main_vbox;
  GtkWidget *menubar1;
  GtkWidget *session_menu;
  GtkWidget *session_menu_menu;
  GtkWidget *session_reload;
  GtkWidget *image2696;
  GtkWidget *session_errors;
  GtkWidget *image2697;
  GtkWidget *separator7;
  GtkWidget *session_check;
  GtkWidget *image2698;
  GtkWidget *session_properties;
  GtkWidget *image2699;
  GtkWidget *separatormenuitem1;
  GtkWidget *session_quit;
  GtkWidget *execution_menu;
  GtkWidget *execution_menu_menu;
  GtkWidget *execution_reset;
  GtkWidget *image2700;
  GtkWidget *execution_go;
  GtkWidget *image2701;
  GtkWidget *execution_step;
  GtkWidget *image2702;
  GtkWidget *execution_abort;
  GtkWidget *image2703;
  GtkWidget *debug_menu;
  GtkWidget *debug_menu_menu;
  GtkWidget *debug_breakpoint;
  GtkWidget *image2704;
  GtkWidget *debug_skip;
  GtkWidget *image2705;
  GtkWidget *debug_clear;
  GtkWidget *image2706;
  GtkWidget *separator5;
  GtkWidget *debug_perl;
  GtkWidget *results_menu;
  GtkWidget *results_menu_menu;
  GtkWidget *results_verdicts;
  GtkWidget *image2707;
  GtkWidget *results_log;
  GtkWidget *image2708;
  GtkWidget *separator3;
  GtkWidget *results_report_options;
  GtkWidget *image2709;
  GtkWidget *results_build_report;
  GtkWidget *image2710;
  GtkWidget *results_view_report;
  GtkWidget *image2711;
  GtkWidget *system_menu;
  GtkWidget *system_menu_menu;
  GtkWidget *system_start_services;
  GtkWidget *image2712;
  GtkWidget *system_stop_services;
  GtkWidget *image2713;
  GtkWidget *separator1;
  GtkWidget *system_start_manual;
  GtkWidget *image2714;
  GtkWidget *system_stop_manual;
  GtkWidget *image2715;
  GtkWidget *help_menu;
  GtkWidget *help_menu_menu;
  GtkWidget *help_about;
  GtkWidget *hbox49;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *tool_reset;
  GtkWidget *tool_go;
  GtkWidget *tool_step;
  GtkWidget *tool_abort;
  GtkWidget *separatortoolitem1;
  GtkWidget *tool_breakpoint;
  GtkWidget *tool_skip;
  GtkWidget *tool_clear;
  GtkWidget *separatortoolitem2;
  GtkWidget *tool_verdicts;
  GtkWidget *tool_log;
  GtkWidget *tool_report;
  GtkWidget *main_pixmap;
  GtkWidget *main_hbox;
  GtkWidget *hpaned1;
  GtkWidget *tree_vbox;
  GtkWidget *tree_scroll;
  GtkWidget *tree_view;
  GtkWidget *table7;
  GtkWidget *label41;
  GtkWidget *hbox23;
  GtkWidget *system_label;
  GtkWidget *label7;
  GtkWidget *hbox17;
  GtkWidget *run_perl_pixmap;
  GtkWidget *run_label;
  GtkWidget *run_label2;
  GtkWidget *case_vbox;
  GtkWidget *case_name;
  GtkWidget *case_output_scroll;
  GtkWidget *case_output;
  GtkWidget *label13;
  GtkWidget *input_expander;
  GtkWidget *input_box;
  GtkWidget *scrolledwindow3;
  GtkWidget *input_textview;
  GtkWidget *hbuttonbox3;
  GtkWidget *input_passed;
  GtkWidget *alignment23;
  GtkWidget *hbox69;
  GtkWidget *image2693;
  GtkWidget *label77;
  GtkWidget *input_failed;
  GtkWidget *alignment24;
  GtkWidget *hbox70;
  GtkWidget *image2694;
  GtkWidget *label78;
  GtkWidget *input_inconclusive;
  GtkWidget *alignment25;
  GtkWidget *hbox71;
  GtkWidget *image2695;
  GtkWidget *label79;
  GtkWidget *label74;
  GtkWidget *validation_expander;
  GtkWidget *validation_eventbox;
  GtkWidget *validation_box;
  GtkWidget *validation_updated;
  GtkWidget *hbox41;
  GtkWidget *validation_last;
  GtkWidget *validation_script_modified;
  GtkWidget *hbox40;
  GtkWidget *validation_icon;
  GtkWidget *validation_script;
  GtkWidget *label73;
  GtkWidget *case_button_box;
  GtkWidget *case_spot_tree;
  GtkWidget *alignment17;
  GtkWidget *hbox63;
  GtkWidget *image2455;
  GtkWidget *label69;
  GtkWidget *case_spot_log;
  GtkWidget *alignment3;
  GtkWidget *hbox26;
  GtkWidget *image3;
  GtkWidget *label18;
  GtkWidget *report_vbox;
  GtkWidget *frame_progress;
  GtkWidget *vbox8;
  GtkWidget *vbox_total;
  GtkWidget *hbox_total;
  GtkWidget *report_total_label;
  GtkWidget *report_total_value;
  GtkWidget *table_total;
  GtkWidget *report_executed_pixmap;
  GtkWidget *report_executed_slider;
  GtkWidget *report_skip_pixmap;
  GtkWidget *report_skip_slider;
  GtkWidget *hseparator2;
  GtkWidget *vbox_significant;
  GtkWidget *hbox_significant;
  GtkWidget *report_significant_label;
  GtkWidget *report_significant_value;
  GtkWidget *table_significant;
  GtkWidget *report_passed_pixmap;
  GtkWidget *report_failed_pixmap;
  GtkWidget *report_inconclusive_pixmap;
  GtkWidget *report_passed_slider;
  GtkWidget *report_failed_slider;
  GtkWidget *report_inconclusive_slider;
  GtkWidget *main_status;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (main_window), _("TestFarm Runner"));
  gtk_window_set_default_size (GTK_WINDOW (main_window), -1, 550);
  main_window_icon_pixbuf = create_pixbuf ("testfarm.png");
  if (main_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (main_window), main_window_icon_pixbuf);
      gdk_pixbuf_unref (main_window_icon_pixbuf);
    }

  main_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (main_vbox);
  gtk_container_add (GTK_CONTAINER (main_window), main_vbox);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (main_vbox), menubar1, FALSE, FALSE, 0);

  session_menu = gtk_menu_item_new_with_mnemonic (_("_Session"));
  gtk_widget_show (session_menu);
  gtk_container_add (GTK_CONTAINER (menubar1), session_menu);

  session_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (session_menu), session_menu_menu);

  session_reload = gtk_image_menu_item_new_with_mnemonic (_("_Reload Test Tree"));
  gtk_widget_show (session_reload);
  gtk_container_add (GTK_CONTAINER (session_menu_menu), session_reload);

  image2696 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image2696);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (session_reload), image2696);

  session_errors = gtk_image_menu_item_new_with_mnemonic (_("_Show Load Errors"));
  gtk_widget_show (session_errors);
  gtk_container_add (GTK_CONTAINER (session_menu_menu), session_errors);

  image2697 = gtk_image_new_from_stock ("gtk-missing-image", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image2697);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (session_errors), image2697);

  separator7 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator7);
  gtk_container_add (GTK_CONTAINER (session_menu_menu), separator7);
  gtk_widget_set_sensitive (separator7, FALSE);

  session_check = gtk_image_menu_item_new_with_mnemonic (_("_Check Files"));
  gtk_widget_show (session_check);
  gtk_container_add (GTK_CONTAINER (session_menu_menu), session_check);

  image2698 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image2698);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (session_check), image2698);

  session_properties = gtk_image_menu_item_new_with_mnemonic (_("_Properties"));
  gtk_widget_show (session_properties);
  gtk_container_add (GTK_CONTAINER (session_menu_menu), session_properties);

  image2699 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image2699);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (session_properties), image2699);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (session_menu_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  session_quit = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (session_quit);
  gtk_container_add (GTK_CONTAINER (session_menu_menu), session_quit);

  execution_menu = gtk_menu_item_new_with_mnemonic (_("_Execution"));
  gtk_widget_show (execution_menu);
  gtk_container_add (GTK_CONTAINER (menubar1), execution_menu);

  execution_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (execution_menu), execution_menu_menu);

  execution_reset = gtk_image_menu_item_new_with_mnemonic (_("_Reset"));
  gtk_widget_show (execution_reset);
  gtk_container_add (GTK_CONTAINER (execution_menu_menu), execution_reset);

  image2700 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image2700);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (execution_reset), image2700);

  execution_go = gtk_image_menu_item_new_with_mnemonic (_("_Go"));
  gtk_widget_show (execution_go);
  gtk_container_add (GTK_CONTAINER (execution_menu_menu), execution_go);

  image2701 = create_pixmap (main_window, "go.png");
  gtk_widget_show (image2701);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (execution_go), image2701);

  execution_step = gtk_image_menu_item_new_with_mnemonic (_("_Step"));
  gtk_widget_show (execution_step);
  gtk_container_add (GTK_CONTAINER (execution_menu_menu), execution_step);

  image2702 = create_pixmap (main_window, "step.png");
  gtk_widget_show (image2702);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (execution_step), image2702);

  execution_abort = gtk_image_menu_item_new_with_mnemonic (_("_Abort"));
  gtk_widget_show (execution_abort);
  gtk_container_add (GTK_CONTAINER (execution_menu_menu), execution_abort);

  image2703 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image2703);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (execution_abort), image2703);

  debug_menu = gtk_menu_item_new_with_mnemonic (_("_Debug"));
  gtk_widget_show (debug_menu);
  gtk_container_add (GTK_CONTAINER (menubar1), debug_menu);

  debug_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (debug_menu), debug_menu_menu);

  debug_breakpoint = gtk_image_menu_item_new_with_mnemonic (_("Toggle _Breakpoint"));
  gtk_widget_show (debug_breakpoint);
  gtk_container_add (GTK_CONTAINER (debug_menu_menu), debug_breakpoint);

  image2704 = create_pixmap (main_window, "breakpoint.png");
  gtk_widget_show (image2704);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (debug_breakpoint), image2704);

  debug_skip = gtk_image_menu_item_new_with_mnemonic (_("Toggle _Force Skip"));
  gtk_widget_show (debug_skip);
  gtk_container_add (GTK_CONTAINER (debug_menu_menu), debug_skip);

  image2705 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image2705);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (debug_skip), image2705);

  debug_clear = gtk_image_menu_item_new_with_mnemonic (_("_Clear Break/Skip Flags"));
  gtk_widget_show (debug_clear);
  gtk_container_add (GTK_CONTAINER (debug_menu_menu), debug_clear);

  image2706 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image2706);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (debug_clear), image2706);

  separator5 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator5);
  gtk_container_add (GTK_CONTAINER (debug_menu_menu), separator5);
  gtk_widget_set_sensitive (separator5, FALSE);

  debug_perl = gtk_check_menu_item_new_with_mnemonic (_("Enable PERL _Debugger"));
  gtk_widget_show (debug_perl);
  gtk_container_add (GTK_CONTAINER (debug_menu_menu), debug_perl);

  results_menu = gtk_menu_item_new_with_mnemonic (_("_Results"));
  gtk_widget_show (results_menu);
  gtk_container_add (GTK_CONTAINER (menubar1), results_menu);

  results_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (results_menu), results_menu_menu);

  results_verdicts = gtk_image_menu_item_new_with_mnemonic (_("_Verdicts"));
  gtk_widget_show (results_verdicts);
  gtk_container_add (GTK_CONTAINER (results_menu_menu), results_verdicts);

  image2707 = create_pixmap (main_window, "list.png");
  gtk_widget_show (image2707);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (results_verdicts), image2707);

  results_log = gtk_image_menu_item_new_with_mnemonic (_("_Log Viewer"));
  gtk_widget_show (results_log);
  gtk_container_add (GTK_CONTAINER (results_menu_menu), results_log);

  image2708 = create_pixmap (main_window, "log.png");
  gtk_widget_show (image2708);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (results_log), image2708);

  separator3 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator3);
  gtk_container_add (GTK_CONTAINER (results_menu_menu), separator3);
  gtk_widget_set_sensitive (separator3, FALSE);

  results_report_options = gtk_image_menu_item_new_with_mnemonic (_("Report _Config"));
  gtk_widget_show (results_report_options);
  gtk_container_add (GTK_CONTAINER (results_menu_menu), results_report_options);
  gtk_tooltips_set_tip (tooltips, results_report_options, _("Configure HTML Test Report layout"), NULL);

  image2709 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image2709);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (results_report_options), image2709);

  results_build_report = gtk_image_menu_item_new_with_mnemonic (_("_Build Report"));
  gtk_widget_show (results_build_report);
  gtk_container_add (GTK_CONTAINER (results_menu_menu), results_build_report);
  gtk_tooltips_set_tip (tooltips, results_build_report, _("Build HTML Test Report"), NULL);

  image2710 = gtk_image_new_from_stock ("gtk-convert", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image2710);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (results_build_report), image2710);

  results_view_report = gtk_image_menu_item_new_with_mnemonic (_("_View Report"));
  gtk_widget_show (results_view_report);
  gtk_container_add (GTK_CONTAINER (results_menu_menu), results_view_report);
  gtk_tooltips_set_tip (tooltips, results_view_report, _("Build and Show HTML Test Report"), NULL);

  image2711 = create_pixmap (main_window, "view.png");
  gtk_widget_show (image2711);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (results_view_report), image2711);

  system_menu = gtk_menu_item_new_with_mnemonic (_("_System"));
  gtk_widget_show (system_menu);
  gtk_container_add (GTK_CONTAINER (menubar1), system_menu);

  system_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (system_menu), system_menu_menu);

  system_start_services = gtk_image_menu_item_new_with_mnemonic (_("Start Services"));
  gtk_widget_show (system_start_services);
  gtk_container_add (GTK_CONTAINER (system_menu_menu), system_start_services);
  gtk_tooltips_set_tip (tooltips, system_start_services, _("Start System Services in AUTO mode"), NULL);

  image2712 = create_pixmap (main_window, "start.png");
  gtk_widget_show (image2712);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (system_start_services), image2712);

  system_stop_services = gtk_image_menu_item_new_with_mnemonic (_("Stop services"));
  gtk_widget_show (system_stop_services);
  gtk_container_add (GTK_CONTAINER (system_menu_menu), system_stop_services);
  gtk_tooltips_set_tip (tooltips, system_stop_services, _("Stop System Services"), NULL);

  image2713 = create_pixmap (main_window, "stop.png");
  gtk_widget_show (image2713);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (system_stop_services), image2713);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (system_menu_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  system_start_manual = gtk_image_menu_item_new_with_mnemonic (_("Start Manual Interface"));
  gtk_widget_show (system_start_manual);
  gtk_container_add (GTK_CONTAINER (system_menu_menu), system_start_manual);
  gtk_tooltips_set_tip (tooltips, system_start_manual, _("Start Manual User Interface"), NULL);

  image2714 = create_pixmap (main_window, "start.png");
  gtk_widget_show (image2714);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (system_start_manual), image2714);

  system_stop_manual = gtk_image_menu_item_new_with_mnemonic (_("Stop Manual Interface"));
  gtk_widget_show (system_stop_manual);
  gtk_container_add (GTK_CONTAINER (system_menu_menu), system_stop_manual);
  gtk_tooltips_set_tip (tooltips, system_stop_manual, _("Stop Manual User Interface"), NULL);

  image2715 = create_pixmap (main_window, "stop.png");
  gtk_widget_show (image2715);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (system_stop_manual), image2715);

  help_menu = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (help_menu);
  gtk_container_add (GTK_CONTAINER (menubar1), help_menu);

  help_menu_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help_menu), help_menu_menu);

  help_about = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (help_about);
  gtk_container_add (GTK_CONTAINER (help_menu_menu), help_about);

  hbox49 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox49);
  gtk_box_pack_start (GTK_BOX (main_vbox), hbox49, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox49), 5);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (hbox49), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  gtk_toolbar_set_show_arrow (GTK_TOOLBAR (toolbar1), FALSE);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-refresh", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  tool_reset = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Reset"));
  gtk_widget_show (tool_reset);
  gtk_container_add (GTK_CONTAINER (toolbar1), tool_reset);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tool_reset), tooltips, _("Reset execution to the root of the Test Tree"), NULL);

  tmp_image = create_pixmap (main_window, "go.png");
  gtk_widget_show (tmp_image);
  tool_go = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Go"));
  gtk_widget_show (tool_go);
  gtk_container_add (GTK_CONTAINER (toolbar1), tool_go);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tool_go), tooltips, _("Start Execution"), NULL);

  tmp_image = create_pixmap (main_window, "step.png");
  gtk_widget_show (tmp_image);
  tool_step = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Step"));
  gtk_widget_show (tool_step);
  gtk_container_add (GTK_CONTAINER (toolbar1), tool_step);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tool_step), tooltips, _("Execute one Test Case"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-stop", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  tool_abort = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Abort"));
  gtk_widget_show (tool_abort);
  gtk_container_add (GTK_CONTAINER (toolbar1), tool_abort);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tool_abort), tooltips, _("Abort Execution"), NULL);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem1);

  tmp_image = create_pixmap (main_window, "breakpoint.png");
  gtk_widget_show (tmp_image);
  tool_breakpoint = (GtkWidget*) gtk_tool_button_new (tmp_image, _("BrkPt"));
  gtk_widget_show (tool_breakpoint);
  gtk_container_add (GTK_CONTAINER (toolbar1), tool_breakpoint);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tool_breakpoint), tooltips, _("Toggle Breakpoint on selected Test Case"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-redo", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  tool_skip = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Skip"));
  gtk_widget_show (tool_skip);
  gtk_container_add (GTK_CONTAINER (toolbar1), tool_skip);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tool_skip), tooltips, _("Toggle Skip Flag on selected Test Case or Sequence"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-clear", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  tool_clear = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Clear"));
  gtk_widget_show (tool_clear);
  gtk_container_add (GTK_CONTAINER (toolbar1), tool_clear);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tool_clear), tooltips, _("Clear all Breakpoints and Skip Flags"), NULL);

  separatortoolitem2 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem2);

  tmp_image = create_pixmap (main_window, "list.png");
  gtk_widget_show (tmp_image);
  tool_verdicts = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Verdicts"));
  gtk_widget_show (tool_verdicts);
  gtk_container_add (GTK_CONTAINER (toolbar1), tool_verdicts);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tool_verdicts), tooltips, _("Show sorted list of Verdicts"), NULL);

  tmp_image = create_pixmap (main_window, "log.png");
  gtk_widget_show (tmp_image);
  tool_log = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Log"));
  gtk_widget_show (tool_log);
  gtk_container_add (GTK_CONTAINER (toolbar1), tool_log);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tool_log), tooltips, _("Raise the Log Viewer"), NULL);

  tmp_image = create_pixmap (main_window, "view.png");
  gtk_widget_show (tmp_image);
  tool_report = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Report"));
  gtk_widget_show (tool_report);
  gtk_container_add (GTK_CONTAINER (toolbar1), tool_report);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (tool_report), tooltips, _("Build and Show HTML Test Report"), NULL);

  main_pixmap = create_pixmap (main_window, NULL);
  gtk_widget_show (main_pixmap);
  gtk_box_pack_end (GTK_BOX (hbox49), main_pixmap, FALSE, FALSE, 0);

  main_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (main_hbox);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_hbox, TRUE, TRUE, 0);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (main_hbox), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 320);

  tree_vbox = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (tree_vbox);
  gtk_paned_pack1 (GTK_PANED (hpaned1), tree_vbox, TRUE, FALSE);
  gtk_container_set_border_width (GTK_CONTAINER (tree_vbox), 5);

  tree_scroll = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (tree_scroll);
  gtk_box_pack_start (GTK_BOX (tree_vbox), tree_scroll, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (tree_scroll), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (tree_scroll), GTK_SHADOW_IN);

  tree_view = gtk_tree_view_new ();
  gtk_widget_show (tree_view);
  gtk_container_add (GTK_CONTAINER (tree_scroll), tree_view);

  table7 = gtk_table_new (1, 2, FALSE);
  gtk_widget_show (table7);
  gtk_box_pack_start (GTK_BOX (tree_vbox), table7, FALSE, FALSE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table7), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table7), 5);

  label41 = gtk_label_new (_("System:"));
  gtk_widget_show (label41);
  gtk_table_attach (GTK_TABLE (table7), label41, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label41), 0, 0.5);

  hbox23 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox23);
  gtk_table_attach (GTK_TABLE (table7), hbox23, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  system_label = gtk_label_new (_("(None)"));
  gtk_widget_show (system_label);
  gtk_box_pack_start (GTK_BOX (hbox23), system_label, FALSE, FALSE, 0);

  label7 = gtk_label_new ("");
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox23), label7, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_CENTER);

  hbox17 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (tree_vbox), hbox17, FALSE, FALSE, 0);

  run_perl_pixmap = create_pixmap (main_window, NULL);
  gtk_widget_show (run_perl_pixmap);
  gtk_box_pack_start (GTK_BOX (hbox17), run_perl_pixmap, FALSE, FALSE, 0);

  run_label = gtk_label_new ("");
  gtk_widget_show (run_label);
  gtk_box_pack_start (GTK_BOX (hbox17), run_label, FALSE, FALSE, 0);

  run_label2 = gtk_label_new ("");
  gtk_widget_show (run_label2);
  gtk_box_pack_start (GTK_BOX (hbox17), run_label2, FALSE, FALSE, 0);

  case_vbox = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (case_vbox);
  gtk_paned_pack2 (GTK_PANED (hpaned1), case_vbox, TRUE, FALSE);
  gtk_container_set_border_width (GTK_CONTAINER (case_vbox), 5);

  case_name = gtk_label_new ("");
  gtk_widget_show (case_name);
  gtk_box_pack_start (GTK_BOX (case_vbox), case_name, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (case_name), GTK_JUSTIFY_FILL);

  case_output_scroll = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (case_output_scroll);
  gtk_box_pack_start (GTK_BOX (case_vbox), case_output_scroll, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (case_output_scroll, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (case_output_scroll), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (case_output_scroll), GTK_SHADOW_IN);

  case_output = gtk_clist_new (1);
  gtk_widget_show (case_output);
  gtk_container_add (GTK_CONTAINER (case_output_scroll), case_output);
  gtk_widget_set_size_request (case_output, 90, -1);
  gtk_clist_set_column_width (GTK_CLIST (case_output), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (case_output));

  label13 = gtk_label_new (_("label13"));
  gtk_widget_show (label13);
  gtk_clist_set_column_widget (GTK_CLIST (case_output), 0, label13);

  input_expander = gtk_expander_new (NULL);
  gtk_widget_show (input_expander);
  gtk_box_pack_start (GTK_BOX (case_vbox), input_expander, FALSE, FALSE, 0);

  input_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (input_box);
  gtk_container_add (GTK_CONTAINER (input_expander), input_box);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (input_box), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_SHADOW_IN);

  input_textview = gtk_text_view_new ();
  gtk_widget_show (input_textview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), input_textview);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (input_box), hbuttonbox3, TRUE, TRUE, 0);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox3), 2);

  input_passed = gtk_button_new ();
  gtk_widget_show (input_passed);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), input_passed);
  GTK_WIDGET_SET_FLAGS (input_passed, GTK_CAN_DEFAULT);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (input_passed), alignment23);

  hbox69 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox69);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox69);

  image2693 = create_pixmap (main_window, "passed.png");
  gtk_widget_show (image2693);
  gtk_box_pack_start (GTK_BOX (hbox69), image2693, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("PASSED"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox69), label77, FALSE, FALSE, 0);

  input_failed = gtk_button_new ();
  gtk_widget_show (input_failed);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), input_failed);
  GTK_WIDGET_SET_FLAGS (input_failed, GTK_CAN_DEFAULT);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (input_failed), alignment24);

  hbox70 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox70);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox70);

  image2694 = create_pixmap (main_window, "failed.png");
  gtk_widget_show (image2694);
  gtk_box_pack_start (GTK_BOX (hbox70), image2694, FALSE, FALSE, 0);

  label78 = gtk_label_new_with_mnemonic (_("FAILED"));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox70), label78, FALSE, FALSE, 0);

  input_inconclusive = gtk_button_new ();
  gtk_widget_show (input_inconclusive);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), input_inconclusive);
  GTK_WIDGET_SET_FLAGS (input_inconclusive, GTK_CAN_DEFAULT);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (input_inconclusive), alignment25);

  hbox71 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox71);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox71);

  image2695 = create_pixmap (main_window, "inconclusive.png");
  gtk_widget_show (image2695);
  gtk_box_pack_start (GTK_BOX (hbox71), image2695, FALSE, FALSE, 0);

  label79 = gtk_label_new_with_mnemonic (_("INCONC."));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (hbox71), label79, FALSE, FALSE, 0);

  label74 = gtk_label_new (_("Verdict Input"));
  gtk_widget_show (label74);
  gtk_expander_set_label_widget (GTK_EXPANDER (input_expander), label74);

  validation_expander = gtk_expander_new (NULL);
  gtk_widget_show (validation_expander);
  gtk_box_pack_start (GTK_BOX (case_vbox), validation_expander, FALSE, FALSE, 0);

  validation_eventbox = gtk_event_box_new ();
  gtk_widget_show (validation_eventbox);
  gtk_container_add (GTK_CONTAINER (validation_expander), validation_eventbox);
  gtk_tooltips_set_tip (tooltips, validation_eventbox, _("Press mouse button to change Validation State"), NULL);

  validation_box = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (validation_box);
  gtk_container_add (GTK_CONTAINER (validation_eventbox), validation_box);
  gtk_table_set_row_spacings (GTK_TABLE (validation_box), 3);
  gtk_table_set_col_spacings (GTK_TABLE (validation_box), 3);

  validation_updated = create_pixmap (main_window, NULL);
  gtk_widget_show (validation_updated);
  gtk_table_attach (GTK_TABLE (validation_box), validation_updated, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  hbox41 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox41);
  gtk_table_attach (GTK_TABLE (validation_box), hbox41, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  validation_last = gtk_label_new (_("Unavailable"));
  gtk_widget_show (validation_last);
  gtk_box_pack_start (GTK_BOX (hbox41), validation_last, FALSE, FALSE, 0);

  validation_script_modified = create_pixmap (main_window, NULL);
  gtk_widget_show (validation_script_modified);
  gtk_table_attach (GTK_TABLE (validation_box), validation_script_modified, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox40 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox40);
  gtk_table_attach (GTK_TABLE (validation_box), hbox40, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  validation_icon = create_pixmap (main_window, NULL);
  gtk_widget_show (validation_icon);
  gtk_box_pack_start (GTK_BOX (hbox40), validation_icon, FALSE, FALSE, 0);

  validation_script = gtk_label_new (_(" "));
  gtk_widget_show (validation_script);
  gtk_box_pack_start (GTK_BOX (hbox40), validation_script, FALSE, FALSE, 0);

  label73 = gtk_label_new (_("Script Validation"));
  gtk_widget_show (label73);
  gtk_expander_set_label_widget (GTK_EXPANDER (validation_expander), label73);
  gtk_misc_set_alignment (GTK_MISC (label73), 0.5, 0.52);

  case_button_box = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (case_button_box);
  gtk_box_pack_start (GTK_BOX (case_vbox), case_button_box, FALSE, FALSE, 0);

  case_spot_tree = gtk_button_new ();
  gtk_widget_show (case_spot_tree);
  gtk_box_pack_start (GTK_BOX (case_button_box), case_spot_tree, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, case_spot_tree, _("Spot this node within the Tree"), NULL);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (case_spot_tree), alignment17);

  hbox63 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox63);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox63);

  image2455 = gtk_image_new_from_stock ("gtk-indent", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2455);
  gtk_box_pack_start (GTK_BOX (hbox63), image2455, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Spot in Tree"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox63), label69, FALSE, FALSE, 0);

  case_spot_log = gtk_button_new ();
  gtk_widget_show (case_spot_log);
  gtk_box_pack_start (GTK_BOX (case_button_box), case_spot_log, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, case_spot_log, _("Spot this test case within the Log"), NULL);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (case_spot_log), alignment3);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox26);

  image3 = create_pixmap (main_window, "log.png");
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox26), image3, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Spot in Log"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox26), label18, FALSE, FALSE, 0);

  report_vbox = gtk_vbox_new (FALSE, 10);
  gtk_widget_show (report_vbox);
  gtk_box_pack_start (GTK_BOX (main_hbox), report_vbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (report_vbox), 5);

  frame_progress = gtk_frame_new (NULL);
  gtk_widget_show (frame_progress);
  gtk_box_pack_start (GTK_BOX (report_vbox), frame_progress, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame_progress), GTK_SHADOW_ETCHED_OUT);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (frame_progress), vbox8);

  vbox_total = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_total);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox_total, FALSE, FALSE, 0);

  hbox_total = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox_total);
  gtk_box_pack_start (GTK_BOX (vbox_total), hbox_total, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox_total), 5);

  report_total_label = gtk_label_new (_("TOTAL:"));
  gtk_widget_show (report_total_label);
  gtk_box_pack_start (GTK_BOX (hbox_total), report_total_label, FALSE, FALSE, 0);

  report_total_value = gtk_label_new (_("0"));
  gtk_widget_show (report_total_value);
  gtk_box_pack_start (GTK_BOX (hbox_total), report_total_value, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (report_total_value), GTK_JUSTIFY_CENTER);

  table_total = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table_total);
  gtk_box_pack_start (GTK_BOX (vbox_total), table_total, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table_total), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table_total), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table_total), 5);

  report_executed_pixmap = gtk_image_new_from_icon_name ("stock_appointment-reminder", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (report_executed_pixmap);
  gtk_table_attach (GTK_TABLE (table_total), report_executed_pixmap, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  report_executed_slider = gtk_progress_bar_new ();
  gtk_widget_show (report_executed_slider);
  gtk_table_attach (GTK_TABLE (table_total), report_executed_slider, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (report_executed_slider), _("Executed"));

  report_skip_pixmap = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (report_skip_pixmap);
  gtk_table_attach (GTK_TABLE (table_total), report_skip_pixmap, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  report_skip_slider = gtk_progress_bar_new ();
  gtk_widget_show (report_skip_slider);
  gtk_table_attach (GTK_TABLE (table_total), report_skip_slider, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (report_skip_slider), _("Skipped"));

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox8), hseparator2, FALSE, FALSE, 0);

  vbox_significant = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_significant);
  gtk_box_pack_start (GTK_BOX (vbox8), vbox_significant, FALSE, FALSE, 0);

  hbox_significant = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox_significant);
  gtk_box_pack_start (GTK_BOX (vbox_significant), hbox_significant, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox_significant), 5);

  report_significant_label = gtk_label_new (_("SIGNIFICANT:"));
  gtk_widget_show (report_significant_label);
  gtk_box_pack_start (GTK_BOX (hbox_significant), report_significant_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (report_significant_label), GTK_JUSTIFY_RIGHT);

  report_significant_value = gtk_label_new (_("0"));
  gtk_widget_show (report_significant_value);
  gtk_box_pack_start (GTK_BOX (hbox_significant), report_significant_value, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (report_significant_value), GTK_JUSTIFY_CENTER);

  table_significant = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table_significant);
  gtk_box_pack_start (GTK_BOX (vbox_significant), table_significant, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table_significant), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table_significant), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table_significant), 5);

  report_passed_pixmap = create_pixmap (main_window, "passed.png");
  gtk_widget_show (report_passed_pixmap);
  gtk_table_attach (GTK_TABLE (table_significant), report_passed_pixmap, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  report_failed_pixmap = create_pixmap (main_window, "failed.png");
  gtk_widget_show (report_failed_pixmap);
  gtk_table_attach (GTK_TABLE (table_significant), report_failed_pixmap, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  report_inconclusive_pixmap = create_pixmap (main_window, "inconclusive.png");
  gtk_widget_show (report_inconclusive_pixmap);
  gtk_table_attach (GTK_TABLE (table_significant), report_inconclusive_pixmap, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  report_passed_slider = gtk_progress_bar_new ();
  gtk_widget_show (report_passed_slider);
  gtk_table_attach (GTK_TABLE (table_significant), report_passed_slider, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (report_passed_slider), _("PASSED"));

  report_failed_slider = gtk_progress_bar_new ();
  gtk_widget_show (report_failed_slider);
  gtk_table_attach (GTK_TABLE (table_significant), report_failed_slider, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (report_failed_slider), _("FAILED"));

  report_inconclusive_slider = gtk_progress_bar_new ();
  gtk_widget_show (report_inconclusive_slider);
  gtk_table_attach (GTK_TABLE (table_significant), report_inconclusive_slider, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (report_inconclusive_slider), _("INCONCLUSIVE"));

  main_status = gtk_statusbar_new ();
  gtk_widget_show (main_status);
  gtk_box_pack_start (GTK_BOX (main_vbox), main_status, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, main_vbox, "main_vbox");
  GLADE_HOOKUP_OBJECT (main_window, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (main_window, session_menu, "session_menu");
  GLADE_HOOKUP_OBJECT (main_window, session_menu_menu, "session_menu_menu");
  GLADE_HOOKUP_OBJECT (main_window, session_reload, "session_reload");
  GLADE_HOOKUP_OBJECT (main_window, image2696, "image2696");
  GLADE_HOOKUP_OBJECT (main_window, session_errors, "session_errors");
  GLADE_HOOKUP_OBJECT (main_window, image2697, "image2697");
  GLADE_HOOKUP_OBJECT (main_window, separator7, "separator7");
  GLADE_HOOKUP_OBJECT (main_window, session_check, "session_check");
  GLADE_HOOKUP_OBJECT (main_window, image2698, "image2698");
  GLADE_HOOKUP_OBJECT (main_window, session_properties, "session_properties");
  GLADE_HOOKUP_OBJECT (main_window, image2699, "image2699");
  GLADE_HOOKUP_OBJECT (main_window, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (main_window, session_quit, "session_quit");
  GLADE_HOOKUP_OBJECT (main_window, execution_menu, "execution_menu");
  GLADE_HOOKUP_OBJECT (main_window, execution_menu_menu, "execution_menu_menu");
  GLADE_HOOKUP_OBJECT (main_window, execution_reset, "execution_reset");
  GLADE_HOOKUP_OBJECT (main_window, image2700, "image2700");
  GLADE_HOOKUP_OBJECT (main_window, execution_go, "execution_go");
  GLADE_HOOKUP_OBJECT (main_window, image2701, "image2701");
  GLADE_HOOKUP_OBJECT (main_window, execution_step, "execution_step");
  GLADE_HOOKUP_OBJECT (main_window, image2702, "image2702");
  GLADE_HOOKUP_OBJECT (main_window, execution_abort, "execution_abort");
  GLADE_HOOKUP_OBJECT (main_window, image2703, "image2703");
  GLADE_HOOKUP_OBJECT (main_window, debug_menu, "debug_menu");
  GLADE_HOOKUP_OBJECT (main_window, debug_menu_menu, "debug_menu_menu");
  GLADE_HOOKUP_OBJECT (main_window, debug_breakpoint, "debug_breakpoint");
  GLADE_HOOKUP_OBJECT (main_window, image2704, "image2704");
  GLADE_HOOKUP_OBJECT (main_window, debug_skip, "debug_skip");
  GLADE_HOOKUP_OBJECT (main_window, image2705, "image2705");
  GLADE_HOOKUP_OBJECT (main_window, debug_clear, "debug_clear");
  GLADE_HOOKUP_OBJECT (main_window, image2706, "image2706");
  GLADE_HOOKUP_OBJECT (main_window, separator5, "separator5");
  GLADE_HOOKUP_OBJECT (main_window, debug_perl, "debug_perl");
  GLADE_HOOKUP_OBJECT (main_window, results_menu, "results_menu");
  GLADE_HOOKUP_OBJECT (main_window, results_menu_menu, "results_menu_menu");
  GLADE_HOOKUP_OBJECT (main_window, results_verdicts, "results_verdicts");
  GLADE_HOOKUP_OBJECT (main_window, image2707, "image2707");
  GLADE_HOOKUP_OBJECT (main_window, results_log, "results_log");
  GLADE_HOOKUP_OBJECT (main_window, image2708, "image2708");
  GLADE_HOOKUP_OBJECT (main_window, separator3, "separator3");
  GLADE_HOOKUP_OBJECT (main_window, results_report_options, "results_report_options");
  GLADE_HOOKUP_OBJECT (main_window, image2709, "image2709");
  GLADE_HOOKUP_OBJECT (main_window, results_build_report, "results_build_report");
  GLADE_HOOKUP_OBJECT (main_window, image2710, "image2710");
  GLADE_HOOKUP_OBJECT (main_window, results_view_report, "results_view_report");
  GLADE_HOOKUP_OBJECT (main_window, image2711, "image2711");
  GLADE_HOOKUP_OBJECT (main_window, system_menu, "system_menu");
  GLADE_HOOKUP_OBJECT (main_window, system_menu_menu, "system_menu_menu");
  GLADE_HOOKUP_OBJECT (main_window, system_start_services, "system_start_services");
  GLADE_HOOKUP_OBJECT (main_window, image2712, "image2712");
  GLADE_HOOKUP_OBJECT (main_window, system_stop_services, "system_stop_services");
  GLADE_HOOKUP_OBJECT (main_window, image2713, "image2713");
  GLADE_HOOKUP_OBJECT (main_window, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (main_window, system_start_manual, "system_start_manual");
  GLADE_HOOKUP_OBJECT (main_window, image2714, "image2714");
  GLADE_HOOKUP_OBJECT (main_window, system_stop_manual, "system_stop_manual");
  GLADE_HOOKUP_OBJECT (main_window, image2715, "image2715");
  GLADE_HOOKUP_OBJECT (main_window, help_menu, "help_menu");
  GLADE_HOOKUP_OBJECT (main_window, help_menu_menu, "help_menu_menu");
  GLADE_HOOKUP_OBJECT (main_window, help_about, "help_about");
  GLADE_HOOKUP_OBJECT (main_window, hbox49, "hbox49");
  GLADE_HOOKUP_OBJECT (main_window, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (main_window, tool_reset, "tool_reset");
  GLADE_HOOKUP_OBJECT (main_window, tool_go, "tool_go");
  GLADE_HOOKUP_OBJECT (main_window, tool_step, "tool_step");
  GLADE_HOOKUP_OBJECT (main_window, tool_abort, "tool_abort");
  GLADE_HOOKUP_OBJECT (main_window, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (main_window, tool_breakpoint, "tool_breakpoint");
  GLADE_HOOKUP_OBJECT (main_window, tool_skip, "tool_skip");
  GLADE_HOOKUP_OBJECT (main_window, tool_clear, "tool_clear");
  GLADE_HOOKUP_OBJECT (main_window, separatortoolitem2, "separatortoolitem2");
  GLADE_HOOKUP_OBJECT (main_window, tool_verdicts, "tool_verdicts");
  GLADE_HOOKUP_OBJECT (main_window, tool_log, "tool_log");
  GLADE_HOOKUP_OBJECT (main_window, tool_report, "tool_report");
  GLADE_HOOKUP_OBJECT (main_window, main_pixmap, "main_pixmap");
  GLADE_HOOKUP_OBJECT (main_window, main_hbox, "main_hbox");
  GLADE_HOOKUP_OBJECT (main_window, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (main_window, tree_vbox, "tree_vbox");
  GLADE_HOOKUP_OBJECT (main_window, tree_scroll, "tree_scroll");
  GLADE_HOOKUP_OBJECT (main_window, tree_view, "tree_view");
  GLADE_HOOKUP_OBJECT (main_window, table7, "table7");
  GLADE_HOOKUP_OBJECT (main_window, label41, "label41");
  GLADE_HOOKUP_OBJECT (main_window, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (main_window, system_label, "system_label");
  GLADE_HOOKUP_OBJECT (main_window, label7, "label7");
  GLADE_HOOKUP_OBJECT (main_window, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (main_window, run_perl_pixmap, "run_perl_pixmap");
  GLADE_HOOKUP_OBJECT (main_window, run_label, "run_label");
  GLADE_HOOKUP_OBJECT (main_window, run_label2, "run_label2");
  GLADE_HOOKUP_OBJECT (main_window, case_vbox, "case_vbox");
  GLADE_HOOKUP_OBJECT (main_window, case_name, "case_name");
  GLADE_HOOKUP_OBJECT (main_window, case_output_scroll, "case_output_scroll");
  GLADE_HOOKUP_OBJECT (main_window, case_output, "case_output");
  GLADE_HOOKUP_OBJECT (main_window, label13, "label13");
  GLADE_HOOKUP_OBJECT (main_window, input_expander, "input_expander");
  GLADE_HOOKUP_OBJECT (main_window, input_box, "input_box");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (main_window, input_textview, "input_textview");
  GLADE_HOOKUP_OBJECT (main_window, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (main_window, input_passed, "input_passed");
  GLADE_HOOKUP_OBJECT (main_window, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (main_window, hbox69, "hbox69");
  GLADE_HOOKUP_OBJECT (main_window, image2693, "image2693");
  GLADE_HOOKUP_OBJECT (main_window, label77, "label77");
  GLADE_HOOKUP_OBJECT (main_window, input_failed, "input_failed");
  GLADE_HOOKUP_OBJECT (main_window, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (main_window, hbox70, "hbox70");
  GLADE_HOOKUP_OBJECT (main_window, image2694, "image2694");
  GLADE_HOOKUP_OBJECT (main_window, label78, "label78");
  GLADE_HOOKUP_OBJECT (main_window, input_inconclusive, "input_inconclusive");
  GLADE_HOOKUP_OBJECT (main_window, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (main_window, hbox71, "hbox71");
  GLADE_HOOKUP_OBJECT (main_window, image2695, "image2695");
  GLADE_HOOKUP_OBJECT (main_window, label79, "label79");
  GLADE_HOOKUP_OBJECT (main_window, label74, "label74");
  GLADE_HOOKUP_OBJECT (main_window, validation_expander, "validation_expander");
  GLADE_HOOKUP_OBJECT (main_window, validation_eventbox, "validation_eventbox");
  GLADE_HOOKUP_OBJECT (main_window, validation_box, "validation_box");
  GLADE_HOOKUP_OBJECT (main_window, validation_updated, "validation_updated");
  GLADE_HOOKUP_OBJECT (main_window, hbox41, "hbox41");
  GLADE_HOOKUP_OBJECT (main_window, validation_last, "validation_last");
  GLADE_HOOKUP_OBJECT (main_window, validation_script_modified, "validation_script_modified");
  GLADE_HOOKUP_OBJECT (main_window, hbox40, "hbox40");
  GLADE_HOOKUP_OBJECT (main_window, validation_icon, "validation_icon");
  GLADE_HOOKUP_OBJECT (main_window, validation_script, "validation_script");
  GLADE_HOOKUP_OBJECT (main_window, label73, "label73");
  GLADE_HOOKUP_OBJECT (main_window, case_button_box, "case_button_box");
  GLADE_HOOKUP_OBJECT (main_window, case_spot_tree, "case_spot_tree");
  GLADE_HOOKUP_OBJECT (main_window, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (main_window, hbox63, "hbox63");
  GLADE_HOOKUP_OBJECT (main_window, image2455, "image2455");
  GLADE_HOOKUP_OBJECT (main_window, label69, "label69");
  GLADE_HOOKUP_OBJECT (main_window, case_spot_log, "case_spot_log");
  GLADE_HOOKUP_OBJECT (main_window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (main_window, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (main_window, image3, "image3");
  GLADE_HOOKUP_OBJECT (main_window, label18, "label18");
  GLADE_HOOKUP_OBJECT (main_window, report_vbox, "report_vbox");
  GLADE_HOOKUP_OBJECT (main_window, frame_progress, "frame_progress");
  GLADE_HOOKUP_OBJECT (main_window, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (main_window, vbox_total, "vbox_total");
  GLADE_HOOKUP_OBJECT (main_window, hbox_total, "hbox_total");
  GLADE_HOOKUP_OBJECT (main_window, report_total_label, "report_total_label");
  GLADE_HOOKUP_OBJECT (main_window, report_total_value, "report_total_value");
  GLADE_HOOKUP_OBJECT (main_window, table_total, "table_total");
  GLADE_HOOKUP_OBJECT (main_window, report_executed_pixmap, "report_executed_pixmap");
  GLADE_HOOKUP_OBJECT (main_window, report_executed_slider, "report_executed_slider");
  GLADE_HOOKUP_OBJECT (main_window, report_skip_pixmap, "report_skip_pixmap");
  GLADE_HOOKUP_OBJECT (main_window, report_skip_slider, "report_skip_slider");
  GLADE_HOOKUP_OBJECT (main_window, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (main_window, vbox_significant, "vbox_significant");
  GLADE_HOOKUP_OBJECT (main_window, hbox_significant, "hbox_significant");
  GLADE_HOOKUP_OBJECT (main_window, report_significant_label, "report_significant_label");
  GLADE_HOOKUP_OBJECT (main_window, report_significant_value, "report_significant_value");
  GLADE_HOOKUP_OBJECT (main_window, table_significant, "table_significant");
  GLADE_HOOKUP_OBJECT (main_window, report_passed_pixmap, "report_passed_pixmap");
  GLADE_HOOKUP_OBJECT (main_window, report_failed_pixmap, "report_failed_pixmap");
  GLADE_HOOKUP_OBJECT (main_window, report_inconclusive_pixmap, "report_inconclusive_pixmap");
  GLADE_HOOKUP_OBJECT (main_window, report_passed_slider, "report_passed_slider");
  GLADE_HOOKUP_OBJECT (main_window, report_failed_slider, "report_failed_slider");
  GLADE_HOOKUP_OBJECT (main_window, report_inconclusive_slider, "report_inconclusive_slider");
  GLADE_HOOKUP_OBJECT (main_window, main_status, "main_status");
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

GtkWidget*
create_report_list_window (void)
{
  GtkWidget *report_list_window;
  GdkPixbuf *report_list_window_icon_pixbuf;
  GtkWidget *report_list_vbox;
  GtkWidget *report_list_scroll;
  GtkWidget *report_list_view;
  GtkWidget *report_list_buttons;
  GtkWidget *report_list_tree;
  GtkWidget *alignment18;
  GtkWidget *hbox64;
  GtkWidget *image2503;
  GtkWidget *label70;
  GtkWidget *report_list_log;
  GtkWidget *alignment13;
  GtkWidget *hbox43;
  GtkWidget *image24;
  GtkWidget *label32;
  GtkWidget *report_list_close;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  report_list_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (report_list_window), _("TestFarm - Test Case list"));
  gtk_window_set_position (GTK_WINDOW (report_list_window), GTK_WIN_POS_MOUSE);
  gtk_window_set_default_size (GTK_WINDOW (report_list_window), -1, 250);
  report_list_window_icon_pixbuf = create_pixbuf ("testfarm.png");
  if (report_list_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (report_list_window), report_list_window_icon_pixbuf);
      gdk_pixbuf_unref (report_list_window_icon_pixbuf);
    }

  report_list_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (report_list_vbox);
  gtk_container_add (GTK_CONTAINER (report_list_window), report_list_vbox);

  report_list_scroll = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (report_list_scroll);
  gtk_box_pack_start (GTK_BOX (report_list_vbox), report_list_scroll, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (report_list_scroll), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  report_list_view = gtk_tree_view_new ();
  gtk_widget_show (report_list_view);
  gtk_container_add (GTK_CONTAINER (report_list_scroll), report_list_view);

  report_list_buttons = gtk_hbutton_box_new ();
  gtk_widget_show (report_list_buttons);
  gtk_box_pack_end (GTK_BOX (report_list_vbox), report_list_buttons, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (report_list_buttons), 5);
  gtk_box_set_spacing (GTK_BOX (report_list_buttons), 10);

  report_list_tree = gtk_button_new ();
  gtk_widget_show (report_list_tree);
  gtk_container_add (GTK_CONTAINER (report_list_buttons), report_list_tree);
  GTK_WIDGET_SET_FLAGS (report_list_tree, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, report_list_tree, _("Spot this test case within the tree"), NULL);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (report_list_tree), alignment18);

  hbox64 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox64);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox64);

  image2503 = gtk_image_new_from_stock ("gtk-indent", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2503);
  gtk_box_pack_start (GTK_BOX (hbox64), image2503, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("Spot in Tree"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox64), label70, FALSE, FALSE, 0);

  report_list_log = gtk_button_new ();
  gtk_widget_show (report_list_log);
  gtk_container_add (GTK_CONTAINER (report_list_buttons), report_list_log);
  GTK_WIDGET_SET_FLAGS (report_list_log, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, report_list_log, _("Spot this test case within the log"), NULL);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (report_list_log), alignment13);

  hbox43 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox43);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox43);

  image24 = create_pixmap (report_list_window, "log.png");
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox43), image24, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Spot in Log"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox43), label32, FALSE, FALSE, 0);

  report_list_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (report_list_close);
  gtk_container_add (GTK_CONTAINER (report_list_buttons), report_list_close);
  GTK_WIDGET_SET_FLAGS (report_list_close, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (report_list_window, report_list_window, "report_list_window");
  GLADE_HOOKUP_OBJECT (report_list_window, report_list_vbox, "report_list_vbox");
  GLADE_HOOKUP_OBJECT (report_list_window, report_list_scroll, "report_list_scroll");
  GLADE_HOOKUP_OBJECT (report_list_window, report_list_view, "report_list_view");
  GLADE_HOOKUP_OBJECT (report_list_window, report_list_buttons, "report_list_buttons");
  GLADE_HOOKUP_OBJECT (report_list_window, report_list_tree, "report_list_tree");
  GLADE_HOOKUP_OBJECT (report_list_window, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (report_list_window, hbox64, "hbox64");
  GLADE_HOOKUP_OBJECT (report_list_window, image2503, "image2503");
  GLADE_HOOKUP_OBJECT (report_list_window, label70, "label70");
  GLADE_HOOKUP_OBJECT (report_list_window, report_list_log, "report_list_log");
  GLADE_HOOKUP_OBJECT (report_list_window, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (report_list_window, hbox43, "hbox43");
  GLADE_HOOKUP_OBJECT (report_list_window, image24, "image24");
  GLADE_HOOKUP_OBJECT (report_list_window, label32, "label32");
  GLADE_HOOKUP_OBJECT (report_list_window, report_list_close, "report_list_close");
  GLADE_HOOKUP_OBJECT_NO_REF (report_list_window, tooltips, "tooltips");

  return report_list_window;
}

GtkWidget*
create_load_report_window (void)
{
  GtkWidget *load_report_window;
  GdkPixbuf *load_report_window_icon_pixbuf;
  GtkWidget *load_report_vbox;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview;
  GtkWidget *load_report_buttons;
  GtkWidget *spot;
  GtkWidget *alignment20;
  GtkWidget *hbox66;
  GtkWidget *image2505;
  GtkWidget *label72;
  GtkWidget *close;

  load_report_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (load_report_window), _("TestFarm - Tree Load Report"));
  gtk_window_set_position (GTK_WINDOW (load_report_window), GTK_WIN_POS_MOUSE);
  gtk_window_set_default_size (GTK_WINDOW (load_report_window), 600, 200);
  load_report_window_icon_pixbuf = create_pixbuf ("testfarm.png");
  if (load_report_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (load_report_window), load_report_window_icon_pixbuf);
      gdk_pixbuf_unref (load_report_window_icon_pixbuf);
    }

  load_report_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (load_report_vbox);
  gtk_container_add (GTK_CONTAINER (load_report_window), load_report_vbox);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (load_report_vbox), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview);

  load_report_buttons = gtk_hbutton_box_new ();
  gtk_widget_show (load_report_buttons);
  gtk_box_pack_end (GTK_BOX (load_report_vbox), load_report_buttons, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (load_report_buttons), 5);
  gtk_box_set_spacing (GTK_BOX (load_report_buttons), 20);

  spot = gtk_button_new ();
  gtk_widget_show (spot);
  gtk_container_add (GTK_CONTAINER (load_report_buttons), spot);
  gtk_widget_set_sensitive (spot, FALSE);
  GTK_WIDGET_SET_FLAGS (spot, GTK_CAN_DEFAULT);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (spot), alignment20);

  hbox66 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox66);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox66);

  image2505 = gtk_image_new_from_stock ("gtk-indent", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2505);
  gtk_box_pack_start (GTK_BOX (hbox66), image2505, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("Spot in Tree"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox66), label72, FALSE, FALSE, 0);

  close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (close);
  gtk_container_add (GTK_CONTAINER (load_report_buttons), close);
  GTK_WIDGET_SET_FLAGS (close, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (load_report_window, load_report_window, "load_report_window");
  GLADE_HOOKUP_OBJECT (load_report_window, load_report_vbox, "load_report_vbox");
  GLADE_HOOKUP_OBJECT (load_report_window, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (load_report_window, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (load_report_window, load_report_buttons, "load_report_buttons");
  GLADE_HOOKUP_OBJECT (load_report_window, spot, "spot");
  GLADE_HOOKUP_OBJECT (load_report_window, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (load_report_window, hbox66, "hbox66");
  GLADE_HOOKUP_OBJECT (load_report_window, image2505, "image2505");
  GLADE_HOOKUP_OBJECT (load_report_window, label72, "label72");
  GLADE_HOOKUP_OBJECT (load_report_window, close, "close");

  return load_report_window;
}

GtkWidget*
create_properties_window (void)
{
  GtkWidget *properties_window;
  GdkPixbuf *properties_window_icon_pixbuf;
  GtkWidget *operator_vbox;
  GtkWidget *warning;
  GtkWidget *warning_hbox;
  GtkWidget *image1399;
  GtkWidget *label;
  GtkWidget *hseparator6;
  GtkWidget *table;
  GtkWidget *label1;
  GtkWidget *release;
  GtkWidget *operator;
  GtkWidget *hbox54;
  GtkWidget *label49;
  GtkWidget *label48;
  GtkWidget *hbox55;
  GtkWidget *label50;
  GtkWidget *label2;
  GtkWidget *hbox56;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *hbox57;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *hbox58;
  GtkWidget *system;
  GtkWidget *label56;
  GtkWidget *hbox59;
  GtkWidget *directory;
  GtkWidget *label58;
  GtkWidget *hbox60;
  GtkWidget *tree;
  GtkWidget *label60;
  GtkWidget *hseparator5;
  GtkWidget *hbuttonbox;
  GtkWidget *validate;
  GtkWidget *alignment9;
  GtkWidget *hbox32;
  GtkWidget *image9;
  GtkWidget *label27;
  GtkWidget *cancel;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  properties_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (properties_window), _("TestFarm - Session Properties"));
  gtk_window_set_position (GTK_WINDOW (properties_window), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (properties_window), TRUE);
  properties_window_icon_pixbuf = create_pixbuf ("testfarm.png");
  if (properties_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (properties_window), properties_window_icon_pixbuf);
      gdk_pixbuf_unref (properties_window_icon_pixbuf);
    }

  operator_vbox = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (operator_vbox);
  gtk_container_add (GTK_CONTAINER (properties_window), operator_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (operator_vbox), 5);

  warning = gtk_vbox_new (FALSE, 0);
  gtk_box_pack_start (GTK_BOX (operator_vbox), warning, FALSE, FALSE, 0);

  warning_hbox = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (warning_hbox);
  gtk_box_pack_start (GTK_BOX (warning), warning_hbox, TRUE, TRUE, 0);

  image1399 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image1399);
  gtk_box_pack_start (GTK_BOX (warning_hbox), image1399, FALSE, FALSE, 0);

  label = gtk_label_new ("");
  gtk_widget_show (label);
  gtk_box_pack_start (GTK_BOX (warning_hbox), label, FALSE, TRUE, 0);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_box_pack_start (GTK_BOX (warning), hseparator6, FALSE, FALSE, 0);

  table = gtk_table_new (5, 2, FALSE);
  gtk_widget_show (table);
  gtk_box_pack_start (GTK_BOX (operator_vbox), table, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table), 5);

  label1 = gtk_label_new (_("Operator name:"));
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table), label1, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_RIGHT);

  release = gtk_entry_new ();
  gtk_widget_show (release);
  gtk_table_attach (GTK_TABLE (table), release, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  operator = gtk_entry_new ();
  gtk_widget_show (operator);
  gtk_table_attach (GTK_TABLE (table), operator, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox54 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox54);
  gtk_table_attach (GTK_TABLE (table), hbox54, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label49 = gtk_label_new ("");
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox54), label49, TRUE, TRUE, 0);

  label48 = gtk_label_new (_("System:"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox54), label48, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label48), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label48), 0, 0.5);

  hbox55 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox55);
  gtk_table_attach (GTK_TABLE (table), hbox55, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label50 = gtk_label_new ("");
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox55), label50, TRUE, TRUE, 0);

  label2 = gtk_label_new (_("Release name:"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox55), label2, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_RIGHT);

  hbox56 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox56);
  gtk_table_attach (GTK_TABLE (table), hbox56, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label51 = gtk_label_new ("");
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox56), label51, TRUE, TRUE, 0);

  label52 = gtk_label_new (_("Directory:"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox56), label52, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label52), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label52), 0, 0.5);

  hbox57 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox57);
  gtk_table_attach (GTK_TABLE (table), hbox57, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label53 = gtk_label_new ("");
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox57), label53, TRUE, TRUE, 0);

  label54 = gtk_label_new (_("Test Suite:"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox57), label54, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label54), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label54), 0, 0.5);

  hbox58 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox58);
  gtk_table_attach (GTK_TABLE (table), hbox58, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  system = gtk_label_new (_("(None)"));
  gtk_widget_show (system);
  gtk_box_pack_start (GTK_BOX (hbox58), system, FALSE, FALSE, 0);

  label56 = gtk_label_new ("");
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox58), label56, TRUE, TRUE, 0);

  hbox59 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox59);
  gtk_table_attach (GTK_TABLE (table), hbox59, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  directory = gtk_label_new ("");
  gtk_widget_show (directory);
  gtk_box_pack_start (GTK_BOX (hbox59), directory, FALSE, FALSE, 0);

  label58 = gtk_label_new ("");
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox59), label58, TRUE, TRUE, 0);

  hbox60 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox60);
  gtk_table_attach (GTK_TABLE (table), hbox60, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  tree = gtk_label_new ("");
  gtk_widget_show (tree);
  gtk_box_pack_start (GTK_BOX (hbox60), tree, FALSE, FALSE, 0);

  label60 = gtk_label_new ("");
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox60), label60, TRUE, TRUE, 0);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_box_pack_start (GTK_BOX (operator_vbox), hseparator5, FALSE, FALSE, 0);

  hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox);
  gtk_box_pack_start (GTK_BOX (operator_vbox), hbuttonbox, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (hbuttonbox, GTK_CAN_DEFAULT);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox), 30);

  validate = gtk_button_new ();
  gtk_widget_show (validate);
  gtk_container_add (GTK_CONTAINER (hbuttonbox), validate);
  GTK_WIDGET_SET_FLAGS (validate, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (validate, "clicked", accel_group,
                              GDK_Return, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (validate), alignment9);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox32);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox32), image9, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Validate"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox32), label27, FALSE, FALSE, 0);

  cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox), cancel);
  GTK_WIDGET_SET_FLAGS (cancel, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (cancel, "clicked", accel_group,
                              GDK_Escape, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (properties_window, properties_window, "properties_window");
  GLADE_HOOKUP_OBJECT (properties_window, operator_vbox, "operator_vbox");
  GLADE_HOOKUP_OBJECT (properties_window, warning, "warning");
  GLADE_HOOKUP_OBJECT (properties_window, warning_hbox, "warning_hbox");
  GLADE_HOOKUP_OBJECT (properties_window, image1399, "image1399");
  GLADE_HOOKUP_OBJECT (properties_window, label, "label");
  GLADE_HOOKUP_OBJECT (properties_window, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (properties_window, table, "table");
  GLADE_HOOKUP_OBJECT (properties_window, label1, "label1");
  GLADE_HOOKUP_OBJECT (properties_window, release, "release");
  GLADE_HOOKUP_OBJECT (properties_window, operator, "operator");
  GLADE_HOOKUP_OBJECT (properties_window, hbox54, "hbox54");
  GLADE_HOOKUP_OBJECT (properties_window, label49, "label49");
  GLADE_HOOKUP_OBJECT (properties_window, label48, "label48");
  GLADE_HOOKUP_OBJECT (properties_window, hbox55, "hbox55");
  GLADE_HOOKUP_OBJECT (properties_window, label50, "label50");
  GLADE_HOOKUP_OBJECT (properties_window, label2, "label2");
  GLADE_HOOKUP_OBJECT (properties_window, hbox56, "hbox56");
  GLADE_HOOKUP_OBJECT (properties_window, label51, "label51");
  GLADE_HOOKUP_OBJECT (properties_window, label52, "label52");
  GLADE_HOOKUP_OBJECT (properties_window, hbox57, "hbox57");
  GLADE_HOOKUP_OBJECT (properties_window, label53, "label53");
  GLADE_HOOKUP_OBJECT (properties_window, label54, "label54");
  GLADE_HOOKUP_OBJECT (properties_window, hbox58, "hbox58");
  GLADE_HOOKUP_OBJECT (properties_window, system, "system");
  GLADE_HOOKUP_OBJECT (properties_window, label56, "label56");
  GLADE_HOOKUP_OBJECT (properties_window, hbox59, "hbox59");
  GLADE_HOOKUP_OBJECT (properties_window, directory, "directory");
  GLADE_HOOKUP_OBJECT (properties_window, label58, "label58");
  GLADE_HOOKUP_OBJECT (properties_window, hbox60, "hbox60");
  GLADE_HOOKUP_OBJECT (properties_window, tree, "tree");
  GLADE_HOOKUP_OBJECT (properties_window, label60, "label60");
  GLADE_HOOKUP_OBJECT (properties_window, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (properties_window, hbuttonbox, "hbuttonbox");
  GLADE_HOOKUP_OBJECT (properties_window, validate, "validate");
  GLADE_HOOKUP_OBJECT (properties_window, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (properties_window, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (properties_window, image9, "image9");
  GLADE_HOOKUP_OBJECT (properties_window, label27, "label27");
  GLADE_HOOKUP_OBJECT (properties_window, cancel, "cancel");

  gtk_widget_grab_focus (hbuttonbox);
  gtk_widget_grab_default (hbuttonbox);
  gtk_window_add_accel_group (GTK_WINDOW (properties_window), accel_group);

  return properties_window;
}

GtkWidget*
create_error_window (void)
{
  GtkWidget *error_window;
  GdkPixbuf *error_window_icon_pixbuf;
  GtkWidget *vbox18;
  GtkWidget *hbox37;
  GtkWidget *image13;
  GtkWidget *label;
  GtkWidget *hseparator3;
  GtkWidget *ok;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  error_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (error_window), _("TestFarm - Error"));
  gtk_window_set_position (GTK_WINDOW (error_window), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (error_window), TRUE);
  error_window_icon_pixbuf = create_pixbuf ("testfarm.png");
  if (error_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (error_window), error_window_icon_pixbuf);
      gdk_pixbuf_unref (error_window_icon_pixbuf);
    }

  vbox18 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox18);
  gtk_container_add (GTK_CONTAINER (error_window), vbox18);

  hbox37 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox37);
  gtk_box_pack_start (GTK_BOX (vbox18), hbox37, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox37), 5);

  image13 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox37), image13, TRUE, TRUE, 0);

  label = gtk_label_new (_(" "));
  gtk_widget_show (label);
  gtk_box_pack_start (GTK_BOX (hbox37), label, FALSE, FALSE, 0);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox18), hseparator3, FALSE, FALSE, 0);

  ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok);
  gtk_box_pack_start (GTK_BOX (vbox18), ok, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (ok), 5);
  gtk_widget_add_accelerator (ok, "clicked", accel_group,
                              GDK_Return, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (ok, "clicked", accel_group,
                              GDK_Escape, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (error_window, error_window, "error_window");
  GLADE_HOOKUP_OBJECT (error_window, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (error_window, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (error_window, image13, "image13");
  GLADE_HOOKUP_OBJECT (error_window, label, "label");
  GLADE_HOOKUP_OBJECT (error_window, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (error_window, ok, "ok");

  gtk_window_add_accel_group (GTK_WINDOW (error_window), accel_group);

  return error_window;
}

GtkWidget*
create_check_window (void)
{
  GtkWidget *check_window;
  GdkPixbuf *check_window_icon_pixbuf;
  GtkWidget *vbox25;
  GtkWidget *vbox26;
  GtkWidget *hbox48;
  GtkWidget *image26;
  GtkWidget *label37;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview;
  GtkWidget *hseparator4;
  GtkWidget *button_box;
  GtkWidget *spot;
  GtkWidget *alignment19;
  GtkWidget *hbox65;
  GtkWidget *image2504;
  GtkWidget *label71;
  GtkWidget *go;
  GtkWidget *alignment16;
  GtkWidget *hbox62;
  GtkWidget *image2000;
  GtkWidget *label68;
  GtkWidget *close;
  GtkWidget *cancel;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  check_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (check_window), _("TestFarm - File Check"));
  gtk_window_set_position (GTK_WINDOW (check_window), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (check_window), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (check_window), -1, 250);
  check_window_icon_pixbuf = create_pixbuf ("testfarm.png");
  if (check_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (check_window), check_window_icon_pixbuf);
      gdk_pixbuf_unref (check_window_icon_pixbuf);
    }

  vbox25 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox25);
  gtk_container_add (GTK_CONTAINER (check_window), vbox25);
  gtk_container_set_border_width (GTK_CONTAINER (vbox25), 5);

  vbox26 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox26);
  gtk_box_pack_start (GTK_BOX (vbox25), vbox26, TRUE, TRUE, 0);

  hbox48 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox48);
  gtk_box_pack_start (GTK_BOX (vbox26), hbox48, FALSE, FALSE, 0);

  image26 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox48), image26, FALSE, FALSE, 0);

  label37 = gtk_label_new (_("The file(s) listed below have been modified.\nYou may need to perform the Suggested Action(s)\nBefore starting the Test Suite."));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox48), label37, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label37), GTK_JUSTIFY_CENTER);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox26), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (vbox25), hseparator4, FALSE, FALSE, 0);

  button_box = gtk_hbox_new (FALSE, 10);
  gtk_widget_show (button_box);
  gtk_box_pack_start (GTK_BOX (vbox25), button_box, FALSE, FALSE, 0);

  spot = gtk_button_new ();
  gtk_widget_show (spot);
  gtk_box_pack_start (GTK_BOX (button_box), spot, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, spot, _("Spot node related to the selected message in the Test Tree"), NULL);
  gtk_widget_add_accelerator (spot, "clicked", accel_group,
                              GDK_space, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (spot), alignment19);

  hbox65 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox65);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox65);

  image2504 = gtk_image_new_from_stock ("gtk-indent", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2504);
  gtk_box_pack_start (GTK_BOX (hbox65), image2504, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("Spot in Tree"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox65), label71, FALSE, FALSE, 0);

  go = gtk_button_new ();
  gtk_box_pack_start (GTK_BOX (button_box), go, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, go, _("Yes, start the Test Suite"), NULL);
  gtk_widget_add_accelerator (go, "clicked", accel_group,
                              GDK_Return, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (go), alignment16);

  hbox62 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox62);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox62);

  image2000 = create_pixmap (check_window, "go.png");
  gtk_widget_show (image2000);
  gtk_box_pack_start (GTK_BOX (hbox62), image2000, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("Go"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox62), label68, FALSE, FALSE, 0);

  close = gtk_button_new_from_stock ("gtk-close");
  gtk_box_pack_end (GTK_BOX (button_box), close, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, close, _("Close the File Check dialog window"), NULL);
  gtk_widget_add_accelerator (close, "clicked", accel_group,
                              GDK_Escape, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_box_pack_end (GTK_BOX (button_box), cancel, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, cancel, _("No, do not start the Test Suite"), NULL);
  gtk_widget_add_accelerator (cancel, "clicked", accel_group,
                              GDK_Escape, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (check_window, check_window, "check_window");
  GLADE_HOOKUP_OBJECT (check_window, vbox25, "vbox25");
  GLADE_HOOKUP_OBJECT (check_window, vbox26, "vbox26");
  GLADE_HOOKUP_OBJECT (check_window, hbox48, "hbox48");
  GLADE_HOOKUP_OBJECT (check_window, image26, "image26");
  GLADE_HOOKUP_OBJECT (check_window, label37, "label37");
  GLADE_HOOKUP_OBJECT (check_window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (check_window, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (check_window, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (check_window, button_box, "button_box");
  GLADE_HOOKUP_OBJECT (check_window, spot, "spot");
  GLADE_HOOKUP_OBJECT (check_window, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (check_window, hbox65, "hbox65");
  GLADE_HOOKUP_OBJECT (check_window, image2504, "image2504");
  GLADE_HOOKUP_OBJECT (check_window, label71, "label71");
  GLADE_HOOKUP_OBJECT (check_window, go, "go");
  GLADE_HOOKUP_OBJECT (check_window, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (check_window, hbox62, "hbox62");
  GLADE_HOOKUP_OBJECT (check_window, image2000, "image2000");
  GLADE_HOOKUP_OBJECT (check_window, label68, "label68");
  GLADE_HOOKUP_OBJECT (check_window, close, "close");
  GLADE_HOOKUP_OBJECT (check_window, cancel, "cancel");
  GLADE_HOOKUP_OBJECT_NO_REF (check_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (check_window), accel_group);

  return check_window;
}

GtkWidget*
create_about_window (void)
{
  GtkWidget *about_window;
  GdkPixbuf *about_window_icon_pixbuf;
  GtkWidget *vbox28;
  GtkWidget *vbox29;
  GtkWidget *vbox30;
  GtkWidget *logo;
  GtkWidget *label66;
  GtkWidget *hseparator8;
  GtkWidget *vbox31;
  GtkWidget *title;
  GtkWidget *version;
  GtkWidget *copyright;
  GtkWidget *hseparator7;
  GtkWidget *hbuttonbox2;
  GtkWidget *ok;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  about_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (about_window), _("TestFarm - About"));
  gtk_window_set_position (GTK_WINDOW (about_window), GTK_WIN_POS_MOUSE);
  gtk_window_set_default_size (GTK_WINDOW (about_window), -1, 250);
  gtk_window_set_resizable (GTK_WINDOW (about_window), FALSE);
  about_window_icon_pixbuf = create_pixbuf ("testfarm.png");
  if (about_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (about_window), about_window_icon_pixbuf);
      gdk_pixbuf_unref (about_window_icon_pixbuf);
    }

  vbox28 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox28);
  gtk_container_add (GTK_CONTAINER (about_window), vbox28);
  gtk_container_set_border_width (GTK_CONTAINER (vbox28), 5);

  vbox29 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox29);
  gtk_box_pack_start (GTK_BOX (vbox28), vbox29, TRUE, TRUE, 0);

  vbox30 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox30);
  gtk_box_pack_start (GTK_BOX (vbox29), vbox30, FALSE, FALSE, 0);

  logo = create_pixmap (about_window, NULL);
  gtk_widget_show (logo);
  gtk_box_pack_start (GTK_BOX (vbox30), logo, TRUE, TRUE, 0);

  label66 = gtk_label_new (_("Automated Testing for Embedded Systems"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (vbox30), label66, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label66), GTK_JUSTIFY_CENTER);

  hseparator8 = gtk_hseparator_new ();
  gtk_widget_show (hseparator8);
  gtk_box_pack_start (GTK_BOX (vbox29), hseparator8, FALSE, FALSE, 0);

  vbox31 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox31);
  gtk_box_pack_start (GTK_BOX (vbox29), vbox31, FALSE, FALSE, 0);

  title = gtk_label_new (_("Test Suite Runner"));
  gtk_widget_show (title);
  gtk_box_pack_start (GTK_BOX (vbox31), title, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (title), GTK_JUSTIFY_CENTER);

  version = gtk_label_new ("");
  gtk_widget_show (version);
  gtk_box_pack_start (GTK_BOX (vbox31), version, FALSE, FALSE, 0);

  copyright = gtk_label_new (_("Copyright Basil Dev 2006"));
  gtk_widget_show (copyright);
  gtk_box_pack_start (GTK_BOX (vbox31), copyright, FALSE, FALSE, 0);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_show (hseparator7);
  gtk_box_pack_start (GTK_BOX (vbox28), hseparator7, FALSE, FALSE, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox28), hbuttonbox2, FALSE, FALSE, 0);

  ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), ok);
  GTK_WIDGET_SET_FLAGS (ok, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (ok, "clicked", accel_group,
                              GDK_Escape, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (about_window, about_window, "about_window");
  GLADE_HOOKUP_OBJECT (about_window, vbox28, "vbox28");
  GLADE_HOOKUP_OBJECT (about_window, vbox29, "vbox29");
  GLADE_HOOKUP_OBJECT (about_window, vbox30, "vbox30");
  GLADE_HOOKUP_OBJECT (about_window, logo, "logo");
  GLADE_HOOKUP_OBJECT (about_window, label66, "label66");
  GLADE_HOOKUP_OBJECT (about_window, hseparator8, "hseparator8");
  GLADE_HOOKUP_OBJECT (about_window, vbox31, "vbox31");
  GLADE_HOOKUP_OBJECT (about_window, title, "title");
  GLADE_HOOKUP_OBJECT (about_window, version, "version");
  GLADE_HOOKUP_OBJECT (about_window, copyright, "copyright");
  GLADE_HOOKUP_OBJECT (about_window, hseparator7, "hseparator7");
  GLADE_HOOKUP_OBJECT (about_window, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (about_window, ok, "ok");

  gtk_window_add_accel_group (GTK_WINDOW (about_window), accel_group);

  return about_window;
}

