/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_report_list_window (void);
GtkWidget* create_load_report_window (void);
GtkWidget* create_properties_window (void);
GtkWidget* create_error_window (void);
GtkWidget* create_check_window (void);
GtkWidget* create_about_window (void);
