#!/bin/bash

##
##    TestFarm Core -- deb package post-installation script
##
##    This file is part of TestFarm,
##    the Test Automation Tool for Embedded Software.
##    Please visit http://www.testfarm.org.
##
##    TestFarm is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.
##
##    TestFarm is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with TestFarm.  If not, see <http://www.gnu.org/licenses/>.
##


update-mime-database /usr/share/mime >/dev/null

ln -sf /opt/testfarm/icons/testfarm.png /usr/share/pixmaps
ln -sf /opt/testfarm/lib/TestFarm /usr/lib/perl5/

function createdir {
  test -d $1 && return
  echo Creating directory $1
  mkdir -m $2 $1 2>/dev/null && chgrp testfarm $1
}
createdir /var/testfarm 0755
createdir /var/testfarm/lib 0775
