/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *hpaned;
  GtkWidget *vbox2;
  GtkWidget *frame3;
  GtkWidget *scrolledwindow4;
  GtkWidget *desktop_treeview;
  GtkWidget *label10;
  GtkWidget *vbox11;
  GtkWidget *toolbar;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *button_input;
  GtkWidget *button_pattern;
  GtkWidget *button_screenshot;
  GtkWidget *frame8;
  GtkWidget *alignment9;
  GtkWidget *refresh_box;
  GtkWidget *refresh_enable;
  GtkWidget *hbox24;
  GtkObject *refresh_period_adj;
  GtkWidget *refresh_period;
  GtkWidget *refresh_now;
  GtkWidget *refresh_geometry;
  GtkWidget *alignment14;
  GtkWidget *hbox32;
  GtkWidget *image20;
  GtkWidget *label45;
  GtkWidget *label37;
  GtkWidget *frame9;
  GtkWidget *alignment10;
  GtkWidget *record_box;
  GtkWidget *hbox23;
  GtkWidget *record_record;
  GtkWidget *image18;
  GtkWidget *record_play;
  GtkWidget *image17;
  GtkWidget *record_pause;
  GtkWidget *image19;
  GtkWidget *record_stop;
  GtkWidget *image14;
  GtkWidget *record_entry;
  GtkWidget *vbox15;
  GtkWidget *record_timing;
  GtkWidget *record_motion;
  GtkWidget *record_cursor;
  GtkWidget *label38;
  GtkWidget *frame13;
  GtkWidget *alignment15;
  GtkWidget *command_box;
  GtkWidget *command_entry;
  GtkWidget *command_send;
  GtkWidget *image21;
  GtkWidget *label46;
  GtkWidget *vbox1;
  GtkWidget *vbox3;
  GtkWidget *label_title;
  GtkWidget *hbox_coords;
  GtkWidget *frame7;
  GtkWidget *hbox19;
  GtkWidget *label34;
  GtkWidget *hbox28;
  GtkWidget *hbox37;
  GtkWidget *label_mouse;
  GtkWidget *label_pixel;
  GtkWidget *frame1;
  GtkWidget *hbox2;
  GtkWidget *label8;
  GtkWidget *hbox38;
  GtkWidget *label_selection;
  GtkWidget *drawing_scrolledwindow;
  GtkWidget *drawing_viewport;
  GtkWidget *drawing_area;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (main_window, 900, 650);
  gtk_container_set_border_width (GTK_CONTAINER (main_window), 5);
  gtk_window_set_title (GTK_WINDOW (main_window), _("TestFarm Virtual User Display"));

  hpaned = gtk_hpaned_new ();
  gtk_widget_show (hpaned);
  gtk_container_add (GTK_CONTAINER (main_window), hpaned);

  vbox2 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox2);
  gtk_paned_pack1 (GTK_PANED (hpaned), vbox2, FALSE, TRUE);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox2), frame3, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_ETCHED_OUT);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (frame3), scrolledwindow4);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow4), 5);
  GTK_WIDGET_UNSET_FLAGS (scrolledwindow4, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  desktop_treeview = gtk_tree_view_new ();
  gtk_widget_show (desktop_treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), desktop_treeview);

  label10 = gtk_label_new (_("Desktops"));
  gtk_widget_show (label10);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label10);

  vbox11 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (vbox2), vbox11, TRUE, TRUE, 0);

  toolbar = gtk_toolbar_new ();
  gtk_widget_show (toolbar);
  gtk_box_pack_start (GTK_BOX (vbox11), toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar), GTK_TOOLBAR_BOTH);
  gtk_toolbar_set_show_arrow (GTK_TOOLBAR (toolbar), FALSE);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar));

  button_input = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (button_input), _("Input\nMode"));
  tmp_image = gtk_image_new_from_stock ("gtk-dialog-info", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (button_input), tmp_image);
  gtk_widget_show (button_input);
  gtk_container_add (GTK_CONTAINER (toolbar), button_input);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_input), tooltips, _("F1 - Toggle Input/Display capture mode"), NULL);
  gtk_widget_add_accelerator (button_input, "clicked", accel_group,
                              GDK_F1, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  tmp_image = gtk_image_new_from_stock ("gtk-select-color", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_pattern = (GtkWidget*) gtk_tool_button_new (tmp_image, _("  Edit\nPatterns"));
  gtk_widget_show (button_pattern);
  gtk_container_add (GTK_CONTAINER (toolbar), button_pattern);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_pattern), tooltips, _("F2 - Edit Display patterns"), NULL);

  button_screenshot = (GtkWidget*) gtk_tool_button_new (NULL, _("Screen\n  Shot"));
  gtk_widget_show (button_screenshot);
  gtk_container_add (GTK_CONTAINER (toolbar), button_screenshot);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (vbox11), frame8, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame8), GTK_SHADOW_ETCHED_OUT);

  alignment9 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (frame8), alignment9);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment9), 3, 3, 3, 3);

  refresh_box = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (refresh_box);
  gtk_container_add (GTK_CONTAINER (alignment9), refresh_box);

  refresh_enable = gtk_check_button_new_with_mnemonic (_("Enable periodic refresh"));
  gtk_widget_show (refresh_enable);
  gtk_box_pack_start (GTK_BOX (refresh_box), refresh_enable, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (refresh_enable, GTK_CAN_FOCUS);
  gtk_button_set_focus_on_click (GTK_BUTTON (refresh_enable), FALSE);

  hbox24 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox24);
  gtk_box_pack_start (GTK_BOX (refresh_box), hbox24, TRUE, TRUE, 0);

  refresh_period_adj = gtk_adjustment_new (1000, 66, 9999, 1, 10, 0);
  refresh_period = gtk_spin_button_new (GTK_ADJUSTMENT (refresh_period_adj), 1, 0);
  gtk_widget_show (refresh_period);
  gtk_box_pack_start (GTK_BOX (hbox24), refresh_period, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (refresh_period, FALSE);
  gtk_tooltips_set_tip (tooltips, refresh_period, _("Refresh period in milliseconds"), NULL);

  refresh_now = gtk_button_new_from_stock ("gtk-refresh");
  gtk_widget_show (refresh_now);
  gtk_box_pack_end (GTK_BOX (hbox24), refresh_now, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (refresh_now, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, refresh_now, _("F3 - Request full display refresh now"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (refresh_now), FALSE);

  refresh_geometry = gtk_button_new ();
  gtk_widget_show (refresh_geometry);
  gtk_box_pack_start (GTK_BOX (refresh_box), refresh_geometry, FALSE, FALSE, 2);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (refresh_geometry), alignment14);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox32);

  image20 = gtk_image_new_from_stock ("gtk-leave-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox32), image20, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Set Active Window"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox32), label45, FALSE, FALSE, 0);

  label37 = gtk_label_new (_("Capture Device"));
  gtk_widget_show (label37);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), label37);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  frame9 = gtk_frame_new (NULL);
  gtk_widget_show (frame9);
  gtk_box_pack_start (GTK_BOX (vbox11), frame9, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame9), GTK_SHADOW_ETCHED_OUT);

  alignment10 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (frame9), alignment10);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment10), 3, 3, 3, 3);

  record_box = gtk_vbox_new (FALSE, 3);
  gtk_widget_show (record_box);
  gtk_container_add (GTK_CONTAINER (alignment10), record_box);

  hbox23 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox23);
  gtk_box_pack_start (GTK_BOX (record_box), hbox23, FALSE, FALSE, 0);

  record_record = gtk_toggle_button_new ();
  gtk_widget_show (record_record);
  gtk_box_pack_start (GTK_BOX (hbox23), record_record, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (record_record, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, record_record, _("F4 - Record"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (record_record), FALSE);

  image18 = gtk_image_new_from_stock ("gtk-media-record", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_container_add (GTK_CONTAINER (record_record), image18);

  record_play = gtk_toggle_button_new ();
  gtk_widget_show (record_play);
  gtk_box_pack_start (GTK_BOX (hbox23), record_play, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (record_play, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, record_play, _("F5 - Playback"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (record_play), FALSE);

  image17 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (record_play), image17);

  record_pause = gtk_toggle_button_new ();
  gtk_widget_show (record_pause);
  gtk_box_pack_start (GTK_BOX (hbox23), record_pause, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (record_pause, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, record_pause, _("F6 - Pause"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (record_pause), FALSE);

  image19 = gtk_image_new_from_stock ("gtk-media-pause", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (record_pause), image19);

  record_stop = gtk_button_new ();
  gtk_widget_show (record_stop);
  gtk_box_pack_start (GTK_BOX (hbox23), record_stop, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (record_stop, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, record_stop, _("F7 - Stop"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (record_stop), FALSE);

  image14 = gtk_image_new_from_stock ("gtk-media-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_container_add (GTK_CONTAINER (record_stop), image14);

  record_entry = gtk_entry_new ();
  gtk_widget_show (record_entry);
  gtk_box_pack_start (GTK_BOX (record_box), record_entry, FALSE, FALSE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (record_entry), 8226);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox15);
  gtk_box_pack_start (GTK_BOX (record_box), vbox15, FALSE, FALSE, 0);

  record_timing = gtk_check_button_new_with_mnemonic (_("Preserve timing"));
  gtk_widget_show (record_timing);
  gtk_box_pack_start (GTK_BOX (vbox15), record_timing, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (record_timing, GTK_CAN_FOCUS);
  gtk_button_set_focus_on_click (GTK_BUTTON (record_timing), FALSE);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (record_timing), TRUE);

  record_motion = gtk_check_button_new_with_mnemonic (_("Record pointer motion"));
  gtk_widget_show (record_motion);
  gtk_box_pack_start (GTK_BOX (vbox15), record_motion, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (record_motion, GTK_CAN_FOCUS);
  gtk_button_set_focus_on_click (GTK_BUTTON (record_motion), FALSE);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (record_motion), TRUE);

  record_cursor = gtk_check_button_new_with_mnemonic (_("Show local pointer cursor"));
  gtk_widget_show (record_cursor);
  gtk_box_pack_start (GTK_BOX (vbox15), record_cursor, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (record_cursor, GTK_CAN_FOCUS);
  gtk_button_set_focus_on_click (GTK_BUTTON (record_cursor), FALSE);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (record_cursor), TRUE);

  label38 = gtk_label_new (_("Input recording"));
  gtk_widget_show (label38);
  gtk_frame_set_label_widget (GTK_FRAME (frame9), label38);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  frame13 = gtk_frame_new (NULL);
  gtk_widget_show (frame13);
  gtk_box_pack_start (GTK_BOX (vbox11), frame13, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame13), GTK_SHADOW_ETCHED_OUT);

  alignment15 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (frame13), alignment15);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment15), 3, 3, 3, 3);

  command_box = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (command_box);
  gtk_container_add (GTK_CONTAINER (alignment15), command_box);

  command_entry = gtk_combo_box_entry_new_text ();
  gtk_widget_show (command_entry);
  gtk_box_pack_start (GTK_BOX (command_box), command_entry, FALSE, FALSE, 0);

  command_send = gtk_button_new ();
  gtk_widget_show (command_send);
  gtk_box_pack_start (GTK_BOX (command_box), command_send, FALSE, FALSE, 0);

  image21 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_container_add (GTK_CONTAINER (command_send), image21);

  label46 = gtk_label_new (_("Manual Command Entry"));
  gtk_widget_show (label46);
  gtk_frame_set_label_widget (GTK_FRAME (frame13), label46);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_paned_pack2 (GTK_PANED (hpaned), vbox1, TRUE, TRUE);

  vbox3 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox3, FALSE, FALSE, 0);

  label_title = gtk_label_new ("");
  gtk_widget_show (label_title);
  gtk_box_pack_start (GTK_BOX (vbox3), label_title, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_title), GTK_JUSTIFY_CENTER);

  hbox_coords = gtk_hbox_new (TRUE, 5);
  gtk_widget_show (hbox_coords);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox_coords, FALSE, FALSE, 0);

  frame7 = gtk_frame_new (NULL);
  gtk_widget_show (frame7);
  gtk_box_pack_start (GTK_BOX (hbox_coords), frame7, TRUE, TRUE, 0);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (frame7), hbox19);
  gtk_container_set_border_width (GTK_CONTAINER (hbox19), 2);

  label34 = gtk_label_new (_("Mouse: "));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox19), label34, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label34), GTK_JUSTIFY_CENTER);

  hbox28 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox28);
  gtk_box_pack_start (GTK_BOX (hbox19), hbox28, TRUE, TRUE, 0);

  hbox37 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox37);
  gtk_box_pack_start (GTK_BOX (hbox28), hbox37, TRUE, TRUE, 0);

  label_mouse = gtk_label_new ("");
  gtk_widget_show (label_mouse);
  gtk_box_pack_start (GTK_BOX (hbox37), label_mouse, FALSE, FALSE, 0);
  gtk_label_set_single_line_mode (GTK_LABEL (label_mouse), TRUE);

  label_pixel = gtk_label_new ("");
  gtk_widget_show (label_pixel);
  gtk_box_pack_end (GTK_BOX (hbox28), label_pixel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label_pixel), GTK_JUSTIFY_RIGHT);
  gtk_label_set_width_chars (GTK_LABEL (label_pixel), 8);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox_coords), frame1, TRUE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (frame1), hbox2);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 2);

  label8 = gtk_label_new (_("Selection: "));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox2), label8, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_CENTER);

  hbox38 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox38);
  gtk_box_pack_start (GTK_BOX (hbox2), hbox38, TRUE, TRUE, 0);

  label_selection = gtk_label_new ("");
  gtk_widget_show (label_selection);
  gtk_box_pack_start (GTK_BOX (hbox38), label_selection, FALSE, FALSE, 0);

  drawing_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (drawing_scrolledwindow);
  gtk_box_pack_start (GTK_BOX (vbox1), drawing_scrolledwindow, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (drawing_scrolledwindow), 5);
  GTK_WIDGET_UNSET_FLAGS (drawing_scrolledwindow, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (drawing_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  drawing_viewport = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (drawing_viewport);
  gtk_container_add (GTK_CONTAINER (drawing_scrolledwindow), drawing_viewport);

  drawing_area = gtk_drawing_area_new ();
  gtk_widget_show (drawing_area);
  gtk_container_add (GTK_CONTAINER (drawing_viewport), drawing_area);
  GTK_WIDGET_SET_FLAGS (drawing_area, GTK_CAN_FOCUS);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, hpaned, "hpaned");
  GLADE_HOOKUP_OBJECT (main_window, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (main_window, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (main_window, desktop_treeview, "desktop_treeview");
  GLADE_HOOKUP_OBJECT (main_window, label10, "label10");
  GLADE_HOOKUP_OBJECT (main_window, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (main_window, toolbar, "toolbar");
  GLADE_HOOKUP_OBJECT (main_window, button_input, "button_input");
  GLADE_HOOKUP_OBJECT (main_window, button_pattern, "button_pattern");
  GLADE_HOOKUP_OBJECT (main_window, button_screenshot, "button_screenshot");
  GLADE_HOOKUP_OBJECT (main_window, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (main_window, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (main_window, refresh_box, "refresh_box");
  GLADE_HOOKUP_OBJECT (main_window, refresh_enable, "refresh_enable");
  GLADE_HOOKUP_OBJECT (main_window, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (main_window, refresh_period, "refresh_period");
  GLADE_HOOKUP_OBJECT (main_window, refresh_now, "refresh_now");
  GLADE_HOOKUP_OBJECT (main_window, refresh_geometry, "refresh_geometry");
  GLADE_HOOKUP_OBJECT (main_window, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (main_window, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (main_window, image20, "image20");
  GLADE_HOOKUP_OBJECT (main_window, label45, "label45");
  GLADE_HOOKUP_OBJECT (main_window, label37, "label37");
  GLADE_HOOKUP_OBJECT (main_window, frame9, "frame9");
  GLADE_HOOKUP_OBJECT (main_window, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (main_window, record_box, "record_box");
  GLADE_HOOKUP_OBJECT (main_window, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (main_window, record_record, "record_record");
  GLADE_HOOKUP_OBJECT (main_window, image18, "image18");
  GLADE_HOOKUP_OBJECT (main_window, record_play, "record_play");
  GLADE_HOOKUP_OBJECT (main_window, image17, "image17");
  GLADE_HOOKUP_OBJECT (main_window, record_pause, "record_pause");
  GLADE_HOOKUP_OBJECT (main_window, image19, "image19");
  GLADE_HOOKUP_OBJECT (main_window, record_stop, "record_stop");
  GLADE_HOOKUP_OBJECT (main_window, image14, "image14");
  GLADE_HOOKUP_OBJECT (main_window, record_entry, "record_entry");
  GLADE_HOOKUP_OBJECT (main_window, vbox15, "vbox15");
  GLADE_HOOKUP_OBJECT (main_window, record_timing, "record_timing");
  GLADE_HOOKUP_OBJECT (main_window, record_motion, "record_motion");
  GLADE_HOOKUP_OBJECT (main_window, record_cursor, "record_cursor");
  GLADE_HOOKUP_OBJECT (main_window, label38, "label38");
  GLADE_HOOKUP_OBJECT (main_window, frame13, "frame13");
  GLADE_HOOKUP_OBJECT (main_window, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (main_window, command_box, "command_box");
  GLADE_HOOKUP_OBJECT (main_window, command_entry, "command_entry");
  GLADE_HOOKUP_OBJECT (main_window, command_send, "command_send");
  GLADE_HOOKUP_OBJECT (main_window, image21, "image21");
  GLADE_HOOKUP_OBJECT (main_window, label46, "label46");
  GLADE_HOOKUP_OBJECT (main_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_window, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (main_window, label_title, "label_title");
  GLADE_HOOKUP_OBJECT (main_window, hbox_coords, "hbox_coords");
  GLADE_HOOKUP_OBJECT (main_window, frame7, "frame7");
  GLADE_HOOKUP_OBJECT (main_window, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (main_window, label34, "label34");
  GLADE_HOOKUP_OBJECT (main_window, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (main_window, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (main_window, label_mouse, "label_mouse");
  GLADE_HOOKUP_OBJECT (main_window, label_pixel, "label_pixel");
  GLADE_HOOKUP_OBJECT (main_window, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (main_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (main_window, label8, "label8");
  GLADE_HOOKUP_OBJECT (main_window, hbox38, "hbox38");
  GLADE_HOOKUP_OBJECT (main_window, label_selection, "label_selection");
  GLADE_HOOKUP_OBJECT (main_window, drawing_scrolledwindow, "drawing_scrolledwindow");
  GLADE_HOOKUP_OBJECT (main_window, drawing_viewport, "drawing_viewport");
  GLADE_HOOKUP_OBJECT (main_window, drawing_area, "drawing_area");
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

GtkWidget*
create_error_window (void)
{
  GtkWidget *error_window;
  GtkWidget *vbox8;
  GtkWidget *frame6;
  GtkWidget *label;
  GtkWidget *hseparator2;
  GtkWidget *hbuttonbox4;
  GtkWidget *ok;

  error_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (error_window), _("TestFarm Virtual User Display: Error message"));
  gtk_window_set_position (GTK_WINDOW (error_window), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (error_window), TRUE);

  vbox8 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (error_window), vbox8);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox8), frame6, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame6), 5);

  label = gtk_label_new ("");
  gtk_widget_show (label);
  gtk_container_add (GTK_CONTAINER (frame6), label);
  gtk_label_set_justify (GTK_LABEL (label), GTK_JUSTIFY_CENTER);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox8), hseparator2, FALSE, FALSE, 0);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (vbox8), hbuttonbox4, FALSE, FALSE, 0);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox4), 30);

  ok = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), ok);
  GTK_WIDGET_SET_FLAGS (ok, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (error_window, error_window, "error_window");
  GLADE_HOOKUP_OBJECT (error_window, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (error_window, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (error_window, label, "label");
  GLADE_HOOKUP_OBJECT (error_window, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (error_window, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (error_window, ok, "ok");

  return error_window;
}

GtkWidget*
create_pattern_window (void)
{
  GtkWidget *pattern_window;
  GtkWidget *vbox10;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *pattern_button_new;
  GtkWidget *pattern_button_remove;
  GtkWidget *pattern_button_copy;
  GtkWidget *tmp_image;
  GtkWidget *pattern_button_copy_all;
  GtkWidget *pattern_button_match;
  GtkWidget *hpaned1;
  GtkWidget *pattern_scrolledwindow;
  GtkWidget *pattern_treeview;
  GtkWidget *edit_box;
  GtkWidget *vbox12;
  GtkWidget *hbox25;
  GtkWidget *label14;
  GtkWidget *edit_id;
  GtkWidget *frame12;
  GtkWidget *alignment13;
  GtkWidget *hbox27;
  GtkWidget *edit_mode_appear;
  GtkWidget *edit_mode_disappear;
  GtkWidget *edit_mode_retrigger;
  GtkWidget *label41;
  GtkWidget *frame11;
  GtkWidget *alignment12;
  GtkWidget *vbox18;
  GtkWidget *hbox35;
  GtkWidget *label48;
  GtkWidget *hbox36;
  GtkWidget *edit_frame;
  GtkWidget *hbox26;
  GtkWidget *hbox9;
  GtkWidget *table3;
  GtkWidget *label20;
  GtkWidget *label22;
  GtkObject *edit_width_adj;
  GtkWidget *edit_width;
  GtkObject *edit_x_adj;
  GtkWidget *edit_x;
  GtkWidget *table4;
  GtkWidget *label21;
  GtkObject *edit_height_adj;
  GtkWidget *edit_height;
  GtkWidget *label23;
  GtkObject *edit_y_adj;
  GtkWidget *edit_y;
  GtkWidget *edit_set;
  GtkWidget *label40;
  GtkWidget *edit_source_frame;
  GtkWidget *alignment11;
  GtkWidget *vbox17;
  GtkWidget *hbox31;
  GtkWidget *label44;
  GtkWidget *edit_source_type;
  GtkWidget *edit_image_box;
  GtkWidget *table5;
  GtkWidget *image_grab;
  GtkWidget *viewer_enable;
  GtkWidget *image_size;
  GtkWidget *hbox30;
  GtkWidget *label43;
  GtkWidget *image_fname;
  GtkWidget *viewer_scrolledwindow;
  GtkWidget *viewer_viewport;
  GtkWidget *viewer_drawingarea;
  GtkWidget *table6;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkWidget *image_fuzz;
  GtkWidget *hbox43;
  GtkObject *image_badpixels_adj;
  GtkWidget *image_badpixels;
  GtkWidget *hbox42;
  GtkWidget *label51;
  GtkObject *image_potential_adj;
  GtkWidget *image_potential;
  GtkWidget *edit_text_box;
  GtkWidget *text_inverse;
  GtkWidget *hbox29;
  GtkWidget *label42;
  GtkWidget *text_regex;
  GtkWidget *edit_source_label;
  GtkWidget *frame14;
  GtkWidget *alignment16;
  GtkWidget *hbox34;
  GtkWidget *edit_mode_brief;
  GtkWidget *label47;
  GtkWidget *hbuttonbox1;
  GtkWidget *edit_apply;
  GtkWidget *edit_revert;
  GtkWidget *alignment8;
  GtkWidget *hbox22;
  GtkWidget *image9;
  GtkWidget *label36;
  GtkWidget *edit_error;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  pattern_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (pattern_window, 800, -1);
  gtk_window_set_title (GTK_WINDOW (pattern_window), _("TestFarm Virtual User Display : pattern management"));
  gtk_window_set_position (GTK_WINDOW (pattern_window), GTK_WIN_POS_MOUSE);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (pattern_window), vbox10);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox10), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  pattern_button_new = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-new");
  gtk_widget_show (pattern_button_new);
  gtk_container_add (GTK_CONTAINER (toolbar1), pattern_button_new);

  pattern_button_remove = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-remove");
  gtk_widget_show (pattern_button_remove);
  gtk_container_add (GTK_CONTAINER (toolbar1), pattern_button_remove);

  pattern_button_copy = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-copy");
  gtk_widget_show (pattern_button_copy);
  gtk_container_add (GTK_CONTAINER (toolbar1), pattern_button_copy);

  tmp_image = gtk_image_new_from_stock ("gtk-index", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  pattern_button_copy_all = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Copy All"));
  gtk_widget_show (pattern_button_copy_all);
  gtk_container_add (GTK_CONTAINER (toolbar1), pattern_button_copy_all);

  tmp_image = gtk_image_new_from_stock ("gtk-find", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  pattern_button_match = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Match"));
  gtk_widget_show (pattern_button_match);
  gtk_container_add (GTK_CONTAINER (toolbar1), pattern_button_match);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox10), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 450);

  pattern_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (pattern_scrolledwindow);
  gtk_paned_pack1 (GTK_PANED (hpaned1), pattern_scrolledwindow, FALSE, TRUE);
  gtk_container_set_border_width (GTK_CONTAINER (pattern_scrolledwindow), 2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (pattern_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (pattern_scrolledwindow), GTK_SHADOW_IN);

  pattern_treeview = gtk_tree_view_new ();
  gtk_widget_show (pattern_treeview);
  gtk_container_add (GTK_CONTAINER (pattern_scrolledwindow), pattern_treeview);

  edit_box = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (edit_box);
  gtk_paned_pack2 (GTK_PANED (hpaned1), edit_box, TRUE, FALSE);
  gtk_container_set_border_width (GTK_CONTAINER (edit_box), 2);

  vbox12 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (edit_box), vbox12, TRUE, TRUE, 0);

  hbox25 = gtk_hbox_new (FALSE, 3);
  gtk_widget_show (hbox25);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox25, FALSE, FALSE, 0);

  label14 = gtk_label_new (_("Id:"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox25), label14, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  edit_id = gtk_entry_new ();
  gtk_widget_show (edit_id);
  gtk_box_pack_start (GTK_BOX (hbox25), edit_id, TRUE, TRUE, 0);

  frame12 = gtk_frame_new (NULL);
  gtk_widget_show (frame12);
  gtk_box_pack_start (GTK_BOX (vbox12), frame12, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame12), GTK_SHADOW_ETCHED_OUT);

  alignment13 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (frame12), alignment13);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment13), 3, 3, 3, 3);

  hbox27 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox27);

  edit_mode_appear = gtk_check_button_new_with_mnemonic (_("Appear"));
  gtk_widget_show (edit_mode_appear);
  gtk_box_pack_start (GTK_BOX (hbox27), edit_mode_appear, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (edit_mode_appear), 2);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (edit_mode_appear), TRUE);

  edit_mode_disappear = gtk_check_button_new_with_mnemonic (_("Disappear"));
  gtk_widget_show (edit_mode_disappear);
  gtk_box_pack_start (GTK_BOX (hbox27), edit_mode_disappear, FALSE, FALSE, 0);

  edit_mode_retrigger = gtk_check_button_new_with_mnemonic (_("Retrigger"));
  gtk_widget_show (edit_mode_retrigger);
  gtk_box_pack_end (GTK_BOX (hbox27), edit_mode_retrigger, FALSE, FALSE, 0);

  label41 = gtk_label_new (_("Detection mode"));
  gtk_widget_show (label41);
  gtk_frame_set_label_widget (GTK_FRAME (frame12), label41);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  frame11 = gtk_frame_new (NULL);
  gtk_widget_show (frame11);
  gtk_box_pack_start (GTK_BOX (vbox12), frame11, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame11), GTK_SHADOW_ETCHED_OUT);

  alignment12 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (frame11), alignment12);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment12), 3, 3, 3, 3);

  vbox18 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox18);
  gtk_container_add (GTK_CONTAINER (alignment12), vbox18);

  hbox35 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox35);
  gtk_box_pack_start (GTK_BOX (vbox18), hbox35, TRUE, TRUE, 0);

  label48 = gtk_label_new (_("Frame:"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox35), label48, FALSE, FALSE, 0);

  hbox36 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox36);
  gtk_box_pack_start (GTK_BOX (hbox35), hbox36, FALSE, FALSE, 0);

  edit_frame = gtk_label_new (_("(root)"));
  gtk_widget_show (edit_frame);
  gtk_box_pack_start (GTK_BOX (hbox36), edit_frame, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (edit_frame), 0.6, 0.49);
  gtk_label_set_single_line_mode (GTK_LABEL (edit_frame), TRUE);

  hbox26 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox26);
  gtk_box_pack_start (GTK_BOX (vbox18), hbox26, TRUE, TRUE, 0);

  hbox9 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (hbox26), hbox9, TRUE, TRUE, 0);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (hbox9), table3, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 2);

  label20 = gtk_label_new (_("Width:"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table3), label20, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_CENTER);

  label22 = gtk_label_new (_("X:"));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table3), label22, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label22), GTK_JUSTIFY_CENTER);

  edit_width_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 0);
  edit_width = gtk_spin_button_new (GTK_ADJUSTMENT (edit_width_adj), 1, 0);
  gtk_widget_show (edit_width);
  gtk_table_attach (GTK_TABLE (table3), edit_width, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (edit_width), TRUE);

  edit_x_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 0);
  edit_x = gtk_spin_button_new (GTK_ADJUSTMENT (edit_x_adj), 1, 0);
  gtk_widget_show (edit_x);
  gtk_table_attach (GTK_TABLE (table3), edit_x, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (edit_x), TRUE);

  table4 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (hbox9), table4, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 2);

  label21 = gtk_label_new (_("Height:"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table4), label21, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_CENTER);

  edit_height_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 0);
  edit_height = gtk_spin_button_new (GTK_ADJUSTMENT (edit_height_adj), 1, 0);
  gtk_widget_show (edit_height);
  gtk_table_attach (GTK_TABLE (table4), edit_height, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (edit_height), TRUE);

  label23 = gtk_label_new (_("Y:"));
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table4), label23, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_CENTER);

  edit_y_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 0);
  edit_y = gtk_spin_button_new (GTK_ADJUSTMENT (edit_y_adj), 1, 0);
  gtk_widget_show (edit_y);
  gtk_table_attach (GTK_TABLE (table4), edit_y, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (edit_y), TRUE);

  edit_set = gtk_button_new_with_mnemonic (_("Set"));
  gtk_widget_show (edit_set);
  gtk_box_pack_start (GTK_BOX (hbox26), edit_set, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, edit_set, _("Set match window from selected area"), NULL);

  label40 = gtk_label_new (_("Match window"));
  gtk_widget_show (label40);
  gtk_frame_set_label_widget (GTK_FRAME (frame11), label40);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  edit_source_frame = gtk_frame_new (NULL);
  gtk_widget_show (edit_source_frame);
  gtk_box_pack_start (GTK_BOX (vbox12), edit_source_frame, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (edit_source_frame), GTK_SHADOW_ETCHED_OUT);

  alignment11 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (edit_source_frame), alignment11);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment11), 3, 3, 3, 3);

  vbox17 = gtk_vbox_new (FALSE, 3);
  gtk_widget_show (vbox17);
  gtk_container_add (GTK_CONTAINER (alignment11), vbox17);

  hbox31 = gtk_hbox_new (FALSE, 10);
  gtk_widget_show (hbox31);
  gtk_box_pack_start (GTK_BOX (vbox17), hbox31, FALSE, FALSE, 0);

  label44 = gtk_label_new (_("Type:"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox31), label44, FALSE, FALSE, 0);

  edit_source_type = gtk_combo_box_new_text ();
  gtk_widget_show (edit_source_type);
  gtk_box_pack_start (GTK_BOX (hbox31), edit_source_type, FALSE, FALSE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (edit_source_type), _("(Please Select)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (edit_source_type), _("Image"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (edit_source_type), _("Text"));

  edit_image_box = gtk_vbox_new (FALSE, 3);
  gtk_box_pack_start (GTK_BOX (vbox17), edit_image_box, TRUE, TRUE, 0);

  table5 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table5);
  gtk_box_pack_start (GTK_BOX (edit_image_box), table5, FALSE, FALSE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table5), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table5), 3);

  image_grab = gtk_button_new_with_mnemonic (_("Grab"));
  gtk_widget_show (image_grab);
  gtk_table_attach (GTK_TABLE (table5), image_grab, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, image_grab, _("Grab selected area"), NULL);

  viewer_enable = gtk_check_button_new_with_mnemonic (_("Preview"));
  gtk_widget_show (viewer_enable);
  gtk_table_attach (GTK_TABLE (table5), viewer_enable, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (viewer_enable), TRUE);

  image_size = gtk_label_new ("");
  gtk_widget_show (image_size);
  gtk_table_attach (GTK_TABLE (table5), image_size, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox30 = gtk_hbox_new (FALSE, 3);
  gtk_widget_show (hbox30);
  gtk_table_attach (GTK_TABLE (table5), hbox30, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label43 = gtk_label_new (_("Image:"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox30), label43, FALSE, FALSE, 0);

  image_fname = gtk_entry_new ();
  gtk_widget_show (image_fname);
  gtk_box_pack_start (GTK_BOX (hbox30), image_fname, TRUE, TRUE, 0);

  viewer_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (viewer_scrolledwindow);
  gtk_box_pack_start (GTK_BOX (edit_image_box), viewer_scrolledwindow, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (viewer_scrolledwindow, GTK_CAN_FOCUS);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (viewer_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewer_viewport = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewer_viewport);
  gtk_container_add (GTK_CONTAINER (viewer_scrolledwindow), viewer_viewport);

  viewer_drawingarea = gtk_drawing_area_new ();
  gtk_widget_show (viewer_drawingarea);
  gtk_container_add (GTK_CONTAINER (viewer_viewport), viewer_drawingarea);

  table6 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table6);
  gtk_box_pack_start (GTK_BOX (edit_image_box), table6, TRUE, TRUE, 0);

  label49 = gtk_label_new (_("Color fuzz:"));
  gtk_widget_show (label49);
  gtk_table_attach (GTK_TABLE (table6), label49, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label50 = gtk_label_new (_("% Bad pixels:"));
  gtk_widget_show (label50);
  gtk_table_attach (GTK_TABLE (table6), label50, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image_fuzz = gtk_entry_new ();
  gtk_widget_show (image_fuzz);
  gtk_table_attach (GTK_TABLE (table6), image_fuzz, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_max_length (GTK_ENTRY (image_fuzz), 7);
  gtk_entry_set_text (GTK_ENTRY (image_fuzz), _("#000000"));
  gtk_entry_set_invisible_char (GTK_ENTRY (image_fuzz), 8226);

  hbox43 = gtk_hbox_new (FALSE, 10);
  gtk_widget_show (hbox43);
  gtk_table_attach (GTK_TABLE (table6), hbox43, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  image_badpixels_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 0);
  image_badpixels = gtk_spin_button_new (GTK_ADJUSTMENT (image_badpixels_adj), 1, 0);
  gtk_widget_show (image_badpixels);
  gtk_box_pack_start (GTK_BOX (hbox43), image_badpixels, TRUE, TRUE, 0);

  hbox42 = gtk_hbox_new (FALSE, 3);
  gtk_widget_show (hbox42);
  gtk_box_pack_start (GTK_BOX (hbox43), hbox42, TRUE, TRUE, 0);

  label51 = gtk_label_new (_("% Potential:"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox42), label51, FALSE, FALSE, 0);

  image_potential_adj = gtk_adjustment_new (100, 1, 100, 1, 10, 0);
  image_potential = gtk_spin_button_new (GTK_ADJUSTMENT (image_potential_adj), 1, 0);
  gtk_widget_show (image_potential);
  gtk_box_pack_start (GTK_BOX (hbox42), image_potential, TRUE, TRUE, 0);

  edit_text_box = gtk_vbox_new (FALSE, 0);
  gtk_box_pack_start (GTK_BOX (vbox17), edit_text_box, TRUE, TRUE, 0);

  text_inverse = gtk_check_button_new_with_mnemonic (_("Inverse video"));
  gtk_widget_show (text_inverse);
  gtk_box_pack_start (GTK_BOX (edit_text_box), text_inverse, FALSE, FALSE, 0);

  hbox29 = gtk_hbox_new (FALSE, 3);
  gtk_widget_show (hbox29);
  gtk_box_pack_start (GTK_BOX (edit_text_box), hbox29, TRUE, TRUE, 0);

  label42 = gtk_label_new (_("RegEx:"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox29), label42, FALSE, FALSE, 0);

  text_regex = gtk_entry_new ();
  gtk_widget_show (text_regex);
  gtk_box_pack_start (GTK_BOX (hbox29), text_regex, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, text_regex, _("Enter the text regular expression to match"), NULL);
  gtk_entry_set_invisible_char (GTK_ENTRY (text_regex), 8226);

  edit_source_label = gtk_label_new (_("Source"));
  gtk_widget_show (edit_source_label);
  gtk_frame_set_label_widget (GTK_FRAME (edit_source_frame), edit_source_label);
  gtk_label_set_use_markup (GTK_LABEL (edit_source_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (edit_source_label), 0.43, 0.5);

  frame14 = gtk_frame_new (NULL);
  gtk_widget_show (frame14);
  gtk_box_pack_start (GTK_BOX (vbox12), frame14, FALSE, FALSE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame14), GTK_SHADOW_ETCHED_OUT);

  alignment16 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (frame14), alignment16);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment16), 3, 3, 3, 3);

  hbox34 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox34);

  edit_mode_brief = gtk_check_button_new_with_mnemonic (_("Brief"));
  gtk_widget_show (edit_mode_brief);
  gtk_box_pack_start (GTK_BOX (hbox34), edit_mode_brief, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (edit_mode_brief), 2);

  label47 = gtk_label_new (_("Output mode"));
  gtk_widget_show (label47);
  gtk_frame_set_label_widget (GTK_FRAME (frame14), label47);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_end (GTK_BOX (edit_box), hbuttonbox1, FALSE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);
  gtk_box_set_spacing (GTK_BOX (hbuttonbox1), 30);

  edit_apply = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (edit_apply);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), edit_apply);
  GTK_WIDGET_SET_FLAGS (edit_apply, GTK_CAN_DEFAULT);

  edit_revert = gtk_button_new ();
  gtk_widget_show (edit_revert);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), edit_revert);
  GTK_WIDGET_SET_FLAGS (edit_revert, GTK_CAN_DEFAULT);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (edit_revert), alignment8);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox22);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox22), image9, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Revert"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox22), label36, FALSE, FALSE, 0);

  edit_error = gtk_label_new ("");
  gtk_widget_show (edit_error);
  gtk_box_pack_end (GTK_BOX (edit_box), edit_error, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (edit_error), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (edit_error), TRUE);
  gtk_misc_set_alignment (GTK_MISC (edit_error), 0.47, 0.5);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (pattern_window, pattern_window, "pattern_window");
  GLADE_HOOKUP_OBJECT (pattern_window, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (pattern_window, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (pattern_window, pattern_button_new, "pattern_button_new");
  GLADE_HOOKUP_OBJECT (pattern_window, pattern_button_remove, "pattern_button_remove");
  GLADE_HOOKUP_OBJECT (pattern_window, pattern_button_copy, "pattern_button_copy");
  GLADE_HOOKUP_OBJECT (pattern_window, pattern_button_copy_all, "pattern_button_copy_all");
  GLADE_HOOKUP_OBJECT (pattern_window, pattern_button_match, "pattern_button_match");
  GLADE_HOOKUP_OBJECT (pattern_window, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (pattern_window, pattern_scrolledwindow, "pattern_scrolledwindow");
  GLADE_HOOKUP_OBJECT (pattern_window, pattern_treeview, "pattern_treeview");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_box, "edit_box");
  GLADE_HOOKUP_OBJECT (pattern_window, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (pattern_window, label14, "label14");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_id, "edit_id");
  GLADE_HOOKUP_OBJECT (pattern_window, frame12, "frame12");
  GLADE_HOOKUP_OBJECT (pattern_window, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_mode_appear, "edit_mode_appear");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_mode_disappear, "edit_mode_disappear");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_mode_retrigger, "edit_mode_retrigger");
  GLADE_HOOKUP_OBJECT (pattern_window, label41, "label41");
  GLADE_HOOKUP_OBJECT (pattern_window, frame11, "frame11");
  GLADE_HOOKUP_OBJECT (pattern_window, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (pattern_window, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (pattern_window, label48, "label48");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox36, "hbox36");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_frame, "edit_frame");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (pattern_window, table3, "table3");
  GLADE_HOOKUP_OBJECT (pattern_window, label20, "label20");
  GLADE_HOOKUP_OBJECT (pattern_window, label22, "label22");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_width, "edit_width");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_x, "edit_x");
  GLADE_HOOKUP_OBJECT (pattern_window, table4, "table4");
  GLADE_HOOKUP_OBJECT (pattern_window, label21, "label21");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_height, "edit_height");
  GLADE_HOOKUP_OBJECT (pattern_window, label23, "label23");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_y, "edit_y");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_set, "edit_set");
  GLADE_HOOKUP_OBJECT (pattern_window, label40, "label40");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_source_frame, "edit_source_frame");
  GLADE_HOOKUP_OBJECT (pattern_window, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (pattern_window, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (pattern_window, label44, "label44");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_source_type, "edit_source_type");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_image_box, "edit_image_box");
  GLADE_HOOKUP_OBJECT (pattern_window, table5, "table5");
  GLADE_HOOKUP_OBJECT (pattern_window, image_grab, "image_grab");
  GLADE_HOOKUP_OBJECT (pattern_window, viewer_enable, "viewer_enable");
  GLADE_HOOKUP_OBJECT (pattern_window, image_size, "image_size");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (pattern_window, label43, "label43");
  GLADE_HOOKUP_OBJECT (pattern_window, image_fname, "image_fname");
  GLADE_HOOKUP_OBJECT (pattern_window, viewer_scrolledwindow, "viewer_scrolledwindow");
  GLADE_HOOKUP_OBJECT (pattern_window, viewer_viewport, "viewer_viewport");
  GLADE_HOOKUP_OBJECT (pattern_window, viewer_drawingarea, "viewer_drawingarea");
  GLADE_HOOKUP_OBJECT (pattern_window, table6, "table6");
  GLADE_HOOKUP_OBJECT (pattern_window, label49, "label49");
  GLADE_HOOKUP_OBJECT (pattern_window, label50, "label50");
  GLADE_HOOKUP_OBJECT (pattern_window, image_fuzz, "image_fuzz");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox43, "hbox43");
  GLADE_HOOKUP_OBJECT (pattern_window, image_badpixels, "image_badpixels");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox42, "hbox42");
  GLADE_HOOKUP_OBJECT (pattern_window, label51, "label51");
  GLADE_HOOKUP_OBJECT (pattern_window, image_potential, "image_potential");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_text_box, "edit_text_box");
  GLADE_HOOKUP_OBJECT (pattern_window, text_inverse, "text_inverse");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (pattern_window, label42, "label42");
  GLADE_HOOKUP_OBJECT (pattern_window, text_regex, "text_regex");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_source_label, "edit_source_label");
  GLADE_HOOKUP_OBJECT (pattern_window, frame14, "frame14");
  GLADE_HOOKUP_OBJECT (pattern_window, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_mode_brief, "edit_mode_brief");
  GLADE_HOOKUP_OBJECT (pattern_window, label47, "label47");
  GLADE_HOOKUP_OBJECT (pattern_window, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_apply, "edit_apply");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_revert, "edit_revert");
  GLADE_HOOKUP_OBJECT (pattern_window, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (pattern_window, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (pattern_window, image9, "image9");
  GLADE_HOOKUP_OBJECT (pattern_window, label36, "label36");
  GLADE_HOOKUP_OBJECT (pattern_window, edit_error, "edit_error");
  GLADE_HOOKUP_OBJECT_NO_REF (pattern_window, tooltips, "tooltips");

  return pattern_window;
}

